;;;; Ambient configuration snapshots and reads.
(in-package #:pp.runtime)

(defun runtime-configuration-error (message &optional (code "runtime.configuration"))
  (if (fboundp 'language-fail) (language-fail message code) (error "~A" message)))

(defun runtime-configuration-value-durable-p (value &optional (seen nil))
  "True when VALUE contains only persistent data, not authority or executable code."
  (when (member value seen :test #'eq) (return-from runtime-configuration-value-durable-p t))
  (let ((seen (cons value seen)))
    (cond ((or (typep value 'value-capability) (typep value 'value-sealed)
               (typep value 'value-closure) (typep value 'value-builtin)
               (typep value 'value-thunk)) nil)
          ((typep value 'value-pair)
           (and (runtime-configuration-value-durable-p (value-pair-car value) seen)
                (runtime-configuration-value-durable-p (value-pair-cdr value) seen)))
          ((typep value 'value-vector)
           (every (lambda (x) (runtime-configuration-value-durable-p x seen))
                  (coerce (value-vector-values value) 'list)))
          ((typep value 'value-map)
           (every (lambda (e) (and (runtime-configuration-value-durable-p (car e) seen)
                                   (runtime-configuration-value-durable-p (cdr e) seen)))
                  (value-map-entries value)))
          ((typep value 'value-set)
           (every (lambda (x) (runtime-configuration-value-durable-p x seen)) (value-set-values value)))
          ((typep value 'value-env-map)
           (every (lambda (e) (runtime-configuration-value-durable-p (cdr e) seen))
                  (value-env-map-bindings value)))
          (t t))))

(defun runtime-configuration-normalize (config)
  (unless (typep config 'value-map)
    (runtime-configuration-error "configuration must be a map"))
  (unless (runtime-configuration-value-durable-p config)
    (runtime-configuration-error "configuration may not contain authority or code" "runtime.authority"))
  (make-vmap (canonical-map-entries (value-map-entries config))))

(defun runtime-configuration-hash (configs)
  (hash-concat (cons "cfg" (mapcar #'hash-value configs))))

(defun runtime-configuration-current ()
  (if (runtime-dynamic-current nil)
      (runtime-dynamic-config)
      (let ((session (runtime-dynamic-session nil)))
        (and session (runtime-session-evaluator session)
             (runtime-evaluator-state-config-stack (runtime-session-evaluator session))))))

(defun runtime-configuration-snapshot (&optional (configs (runtime-configuration-current)))
  (copy-list configs))

(defun runtime-configuration-current-hash ()
  (runtime-configuration-hash (runtime-configuration-current)))

(defun runtime-configuration-lookup (key &optional default default-p)
  (let ((key (cond ((stringp key) key)
                   ((typep key 'value-string) (value-string-value key))
                   ((typep key 'value-symbol) (value-symbol-value key))
                   ((typep key 'value-keyword) (value-keyword-value key))
                   (t nil))))
    (unless key (runtime-configuration-error "configuration key must be text"))
    (multiple-value-bind (value present) (runtime-dynamic-config-lookup key)
      (if present (values value t)
          (if default-p (values default t) (values nil nil))))))
(defun runtime-configuration-read (key &optional default default-p)
  (multiple-value-bind (value present)
      (runtime-configuration-lookup key default default-p)
    (let ((hash (if present (hash-value value) "config-cell:absent"))
          (cell-key (cond ((stringp key) key)
                          ((typep key 'value-string) (value-string-value key))
                          ((typep key 'value-symbol) (value-symbol-value key))
                          ((typep key 'value-keyword) (value-keyword-value key))
                          (t (runtime-configuration-error
                              "configuration key must be text")))))
      (when (fboundp 'runtime-observation-record)
        (runtime-observation-record (make-cell-config cell-key) hash))
      (values value present))))

(defun runtime-configuration-with (config thunk)
  (runtime-dynamic-push-config (runtime-configuration-normalize config))
  (unwind-protect
       (funcall thunk)
    (runtime-dynamic-pop-config)))
(defun runtime-configuration-push (config)
  (runtime-dynamic-push-config (runtime-configuration-normalize config)))
(defun runtime-configuration-pop () (runtime-dynamic-pop-config))
(defun runtime-config-hash (&optional configs) (runtime-configuration-hash (or configs (runtime-configuration-current))))
(defun runtime-config-lookup (key &optional default default-p) (runtime-configuration-lookup key default default-p))
(defun runtime-config-read (key &optional default default-p) (runtime-configuration-read key default default-p))
(defun runtime-config-with (config thunk) (runtime-configuration-with config thunk))
(defun configuration-hash (configs) (runtime-configuration-hash configs))
(defun configuration-lookup (key &optional default default-p)
  (runtime-configuration-lookup key default default-p))
(defun configuration-read (key &optional default default-p)
  (runtime-configuration-read key default default-p))
