const hosts = Number(Deno.args[0] ?? "8"), fanout = Number(Deno.args[1] ?? "2"), seed = Number(Deno.args[2] ?? "0");
if (![hosts, fanout, seed].every(Number.isSafeInteger) || hosts < 1 || fanout < 1 || seed < 0) throw new Error("usage: generate HOSTS FANOUT SEED");
const hostFields = Array.from({ length: hosts }, (_, index) => `h${index}: { cores: 1, store: cold }`).join(",\n    ");
const links: string[] = [];
for (let from = 0; from < hosts; from += 1) for (let offset = 1; offset <= Math.min(fanout, hosts - 1); offset += 1) {
  const to = (from + offset) % hosts; links.push(`{ id: h${from}-h${to}, from: h${from}, to: h${to}, latency: "1ms", bandwidth: "1gbit", loss: "0%" }`);
}
console.log(`# generated by pp-sim-scale v1 hosts=${hosts} fanout=${fanout} seed=${seed}
scenario v1 {
  seed: ${seed}, program: { file: "build.pp", argv: [] },
  hosts: {
    ${hostFields}
  },
  links: [${links.join(",\n    ")}],
  grants: [], actions: [], expect: [{ eventually: { event: "run.finished" } }]
}`);
