#!/usr/bin/env bash
# tests/086 — the manual's code examples are executable under both back ends.
#
# docs/manual/build.pp runs every example while rendering the manual and embeds
# its real output, so a broken example fails the build and the docs cannot
# drift — but that build needs typst and runs outside `dune runtest`. This is
# the typst-free half, on every run: each docs/manual/examples/NAME.pp is
# executed under BOTH back ends and they must agree byte for byte, and each
# must succeed — except the handful that deliberately demonstrate an error,
# which must fail on both. So an example that stops running, or that the two
# engines disagree on, is a red build without waiting for a manual render.
#
# It compares the engines to each other and checks exit intent, NOT against
# docs/manual/captured/ — that directory is a git-ignored build artifact
# (regenerated by scripts/build-manual.sh), absent on a fresh checkout, so it
# is not a committed baseline. Examples run from examples/ so any error text's
# relative NAME.pp:line path is stable. Each back end gets a FRESH store: the
# node examples print from inside a node body, so a shared store would let the
# second engine hit the first's cached node and skip the logged recompute.
set -uo pipefail
. "$(dirname "$0")/lib.sh"
EX="$PWD/docs/manual/examples"

# Examples that demonstrate an error on purpose (a denied capability, an
# ill-typed call): these must FAIL on both back ends; every other example must
# succeed on both.
is_error_demo() { case "$1" in cap-read|type-error|ref-type-error) return 0 ;; *) return 1 ;; esac; }

run_one() {  # BACKEND-FLAG NAME -> sets REPLY to combined out+err, returns exit code
  ( cd "$EX" && HOME=$(mktemp -d) "$PP" $1 "$2.pp" >"$TMP/o" 2>"$TMP/e" )
  local code=$?
  REPLY=$(cat "$TMP/o" "$TMP/e")
  return $code
}

count=0
for f in "$EX"/*.pp; do
  name=$(basename "$f" .pp)
  count=$((count + 1))
  run_one "" "$name"; tw_code=$?; tw=$REPLY
  run_one "--bytecode" "$name"; bc_code=$?; bc=$REPLY
  if [ "$tw" != "$bc" ]; then
    bad "manual-$name" "back ends disagree" "--- tw ---" "$tw" "--- bc ---" "$bc"
  elif is_error_demo "$name"; then
    if [ "$tw_code" != 0 ] && [ "$bc_code" != 0 ]; then ok "manual-$name (error demo)"
    else bad "manual-$name" "expected an error demo to fail on both, got tw=$tw_code bc=$bc_code" "$tw"; fi
  else
    if [ "$tw_code" = 0 ] && [ "$bc_code" = 0 ]; then ok "manual-$name"
    else bad "manual-$name" "example failed (tw=$tw_code bc=$bc_code) — broken or newly an error demo" "$tw"; fi
  fi
done
if [ "$count" -gt 0 ]; then ok "manual-examples-ran ($count under both back ends)"
else echo "FAIL no manual examples found under $EX"; fail=1; fi
exit $fail
