(in-package :pp.kernel)

;;; Cluster-token support is deliberately effect-free.  Paths, secret reads,
;;; writes, and clocks arrive as explicit values/functions; this kernel layer
;;; never opens files, consults HOME, or persists a capability.

(defun cap-token-join-path (directory leaf)
  (if (or (string= directory "")
          (char= (char directory (1- (length directory))) #\/))
      (concatenate 'string directory leaf)
      (concatenate 'string directory "/" leaf)))

(defun cluster-dir (home-directory)
  (check-type home-directory string)
  (cap-token-join-path home-directory ".pp/cluster"))
(defun secret-path (home-directory)
  (cap-token-join-path (cluster-dir home-directory) "secret"))
(defun id-path (home-directory)
  (cap-token-join-path (cluster-dir home-directory) "id"))

(defun cap-token-trim-secret (text)
  (check-type text string)
  (if (and (> (length text) 0)
           (char= (char text (1- (length text))) #\Newline))
      (subseq text 0 (1- (length text)))
      text))

(defun write-secret-file (writer path content)
  "Delegate exclusive 0600 creation to WRITER; no host access is invented."
  (unless (functionp writer)
    (error "WRITE-SECRET-FILE requires an injected writer"))
  (check-type path string)
  (check-type content string)
  (funcall writer path content))

(defun load-secret (reader home-directory)
  (unless (functionp reader)
    (error "LOAD-SECRET requires an injected reader"))
  (cap-token-trim-secret (funcall reader (secret-path home-directory))))
(defun load-cluster-id (reader home-directory)
  (unless (functionp reader)
    (error "LOAD-CLUSTER-ID requires an injected reader"))
  (cap-token-trim-secret (funcall reader (id-path home-directory))))

(defun cap-token-hex-digit (n)
  (char "0123456789abcdef" (logand n #xf)))
(defun cap-token-quote-string (string)
  (check-type string string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for character across string
          for code = (char-code character)
          do (cond ((char= character #\\) (write-string "\\\\" out))
                   ((char= character #\") (write-string "\\\"" out))
                   ((or (< code #x20) (= code #x7f))
                    (write-string "\\x" out)
                    (write-char (cap-token-hex-digit (ash code -4)) out)
                    (write-char (cap-token-hex-digit code) out))
                   (t (write-char character out))))
    (write-char #\" out)))

(defun cap-token-parse-quoted (text start)
  (when (and (< start (length text)) (char= (char text start) #\"))
    (let ((out (make-string-output-stream))
          (i (1+ start)))
      (loop while (< i (length text))
            for character = (char text i)
            do (cond
                 ((char= character #\")
                  (return-from cap-token-parse-quoted
                    (values (get-output-stream-string out) (1+ i))))
                 ((char= character #\\)
                  (when (>= (1+ i) (length text))
                    (return-from cap-token-parse-quoted nil))
                  (let ((next (char text (1+ i))))
                    (case next
                      (#\\ (write-char #\\ out) (incf i))
                      (#\" (write-char #\" out) (incf i))
                      (#\x
                       (when (> (+ i 3) (1- (length text)))
                         (return-from cap-token-parse-quoted nil))
                       (let ((hi (digit-char-p (char text (+ i 2)) 16))
                             (lo (digit-char-p (char text (+ i 3)) 16)))
                         (unless (and hi lo)
                           (return-from cap-token-parse-quoted nil))
                         (write-char (code-char (+ (* hi 16) lo)) out)
                         (incf i 3)))
                      (otherwise
                       (return-from cap-token-parse-quoted nil)))))
                 (t (write-char character out)))
            (incf i)))))

(defun cap-token-read-int (text start)
  (let ((i start)
        (length (length text)))
    (when (and (< i length) (char= (char text i) #\-)) (incf i))
    (let ((digits-start i))
      (loop while (and (< i length)
                       (digit-char-p (char text i) 10)) do (incf i))
      (when (> i digits-start)
        (values (parse-integer text :start start :end i :radix 10)
                i)))))

(defun cap-token-payload (specs cluster-id issued expires)
  (format nil "(cluster-token (~{~A~^ ~}) ~A ~D ~D)"
          (mapcar #'cap-token-quote-string specs)
          (cap-token-quote-string cluster-id) issued expires))

(defun cap-token-octets-from-hex (hex)
  (unless (and (evenp (length hex))
               (every (lambda (c) (digit-char-p c 16)) hex))
    (error "Invalid hexadecimal digest"))
  (let ((result (make-array (/ (length hex) 2)
                            :element-type '(unsigned-byte 8))))
    (loop for i from 0 below (length hex) by 2
          for j from 0
          do (setf (aref result j)
                   (+ (* 16 (digit-char-p (char hex i) 16))
                      (digit-char-p (char hex (1+ i)) 16))))
    result))

(defun cap-token-octets-append (a b)
  (let ((result (make-array (+ (length a) (length b))
                           :element-type '(unsigned-byte 8))))
    (replace result a)
    (replace result b :start1 (length a))
    result))

(defun cap-token-hmac-sha256 (secret payload)
  "HMAC-SHA256 using the kernel SHA implementation and explicit octets."
  (let* ((key (string-octets secret))
         (key (if (> (length key) 64)
                  (cap-token-octets-from-hex (sha256-octets key))
                  key))
         (block (make-array 64 :element-type '(unsigned-byte 8)
                            :initial-element 0)))
    (replace block key)
    (let ((ipad (make-array 64 :element-type '(unsigned-byte 8)))
          (opad (make-array 64 :element-type '(unsigned-byte 8))))
      (loop for i below 64 do
        (setf (aref ipad i) (logxor (aref block i) #x36)
              (aref opad i) (logxor (aref block i) #x5c)))
      (let* ((message (string-octets payload))
             (inner (sha256-octets (cap-token-octets-append ipad message)))
             (outer (sha256-octets
                     (cap-token-octets-append opad
                                              (cap-token-octets-from-hex inner)))))
        outer))))

(defun cap-token-constant-time-equal (a b)
  (and (stringp a) (stringp b)
       (= (length a) (length b))
       (zerop (loop for i below (length a)
                    sum (logxor (char-code (char a i))
                                (char-code (char b i)))))))

(defun mint-capability-token (&key secret cluster-id specs issued ttl-seconds)
  "Mint canonical token text from explicit, already available inputs."
  (check-type secret string)
  (check-type cluster-id string)
  (check-type specs list)
  (unless (every (lambda (spec) (typep spec 'string)) specs)
    (error "Token capability specs must be strings"))
  (check-type issued integer)
  (check-type ttl-seconds integer)
  (let* ((expires (+ issued ttl-seconds))
         (payload (cap-token-payload specs cluster-id issued expires))
         (mac (cap-token-hmac-sha256 secret payload)))
    (format nil "~A ~A)"
            (subseq payload 0 (1- (length payload)))
            (cap-token-quote-string mac))))

(defun cap-token-parse (text)
  (when (stringp text)
    (let* ((length (length text))
           (i 0)
           (prefix "(cluster-token ("))
      (unless (and (>= length (length prefix))
                   (string= prefix text :end2 (length prefix)))
        (return-from cap-token-parse nil))
      (setf i (length prefix))
      (let ((specs nil)
            (spec-ok :continue))
        (if (and (< i length) (char= (char text i) (code-char 41)))
            (progn (incf i) (setf spec-ok :done))
            (loop until (member spec-ok '(:done nil))
                  do (multiple-value-bind (spec next)
                         (cap-token-parse-quoted text i)
                       (if (null next)
                           (setf spec-ok nil)
                           (progn
                             (push spec specs)
                             (setf i next)
                             (cond
                               ((and (< i length)
                                     (char= (char text i) (code-char 41)))
                                (incf i)
                                (setf spec-ok :done))
                               ((and (< i length)
                                     (char= (char text i) #\Space))
                                (incf i))
                               (t (setf spec-ok nil))))))))
        (unless (eq spec-ok :done)
          (return-from cap-token-parse nil))
        (unless (and (< i length) (char= (char text i) #\Space))
          (return-from cap-token-parse nil))
        (incf i)
        (multiple-value-bind (cluster-id next-cluster)
            (cap-token-parse-quoted text i)
          (unless next-cluster (return-from cap-token-parse nil))
          (setf i next-cluster)
          (unless (and (< i length) (char= (char text i) #\Space))
            (return-from cap-token-parse nil))
          (incf i)
          (multiple-value-bind (issued next-issued) (cap-token-read-int text i)
            (unless next-issued (return-from cap-token-parse nil))
            (setf i next-issued)
            (unless (and (< i length) (char= (char text i) #\Space))
              (return-from cap-token-parse nil))
            (incf i)
            (multiple-value-bind (expires next-expires)
                (cap-token-read-int text i)
              (unless next-expires (return-from cap-token-parse nil))
              (setf i next-expires)
              (unless (and (< i length) (char= (char text i) #\Space))
                (return-from cap-token-parse nil))
              (incf i)
              (multiple-value-bind (mac next-mac)
                  (cap-token-parse-quoted text i)
                (unless next-mac (return-from cap-token-parse nil))
                (setf i next-mac)
                (when (and (< i length)
                           (char= (char text i) (code-char 41)))
                  (incf i)
                  (when (= i length)
                    (list (nreverse specs) cluster-id issued expires mac)))))))))))

(defun verify-capability-token (token &key secret cluster-id now realpath)
  "Return two values: capabilities and NIL, or NIL and a rejection string."
  (let ((parsed (cap-token-parse token)))
    (unless parsed
      (return-from verify-capability-token
        (values nil "malformed cluster token (unparseable or foreign format)")))
    (destructuring-bind (specs token-cluster issued expires mac) parsed
      (let ((payload (cap-token-payload specs token-cluster issued expires)))
        (unless (cap-token-constant-time-equal
                 (cap-token-hmac-sha256 secret payload) mac)
          (return-from verify-capability-token
            (values nil "cluster token rejected: MAC mismatch (tampered, or minted under a different cluster secret)")))
        (unless (string= token-cluster cluster-id)
          (return-from verify-capability-token
            (values nil "cluster token rejected: minted for a different cluster id")))
        (unless (and (numberp now) (<= now expires))
          (return-from verify-capability-token
            (values nil (format nil "cluster token rejected: expired at ~D" expires))))
        (handler-case
            (values (mapcar (lambda (spec) (mint-capability spec :realpath realpath)) specs)
                    nil)
          (error (condition)
            (values nil (format nil "cluster token names an invalid capability: ~A"
                                condition))))))))

(defun token-to-caps (token &key secret cluster-id now realpath reader home-directory)
  "Verify with explicit credentials, optionally loaded through injected READER."
  (when (and (null secret) reader home-directory)
    (setf secret (load-secret reader home-directory)))
  (when (and (null cluster-id) reader home-directory)
    (setf cluster-id (load-cluster-id reader home-directory)))
  (verify-capability-token token :secret secret :cluster-id cluster-id
                           :now now :realpath realpath))

;;; Short aliases for token operations.
(defun mint-token (&rest arguments) (apply #'mint-capability-token arguments))
(defun verify-token (&rest arguments) (apply #'verify-capability-token arguments))
(defun token-to-capabilities (&rest arguments) (apply #'token-to-caps arguments))
