(in-package :pp.kernel)

(defstruct (cell-file (:constructor make-cell-file (value))) (value "" :type string))
(defstruct (cell-runtime-file (:constructor make-cell-runtime-file (value))) (value "" :type string))
(defstruct (cell-tool (:constructor make-cell-tool (value))) (value "" :type string))
(defstruct (cell-tree (:constructor make-cell-tree (value))) (value "" :type string))
(defstruct (cell-stat (:constructor make-cell-stat (value))) (value "" :type string))
(defstruct (cell-env (:constructor make-cell-env (value))) (value "" :type string))
(defstruct (cell-argv (:constructor make-cell-argv ())))
(defstruct (cell-config (:constructor make-cell-config (value))) (value "" :type string))
(defstruct (cell-handler (:constructor make-cell-handler (value))) (value "" :type string))
(defstruct (cell-probe (:constructor make-cell-probe (value))) (value "" :type string))
(defstruct (cell-sealed (:constructor make-cell-sealed (value))) (value "" :type string))
(defstruct (cell-node (:constructor make-cell-node (value))) (value "" :type string))
(defstruct (cell-domain (:constructor make-cell-domain (name sub)))
  (name "" :type string) (sub "" :type string))
(defstruct (cell-unknown (:constructor make-cell-unknown (value))) (value "" :type string))
(deftype cell ()
  '(or cell-file cell-runtime-file cell-tool cell-tree cell-stat cell-env cell-argv
       cell-config cell-handler cell-probe cell-sealed cell-node cell-domain cell-unknown))
(defun make-cell (&key kind data name sub)
  (ecase kind
    (:file (make-cell-file (or data ""))) (:runtime-file (make-cell-runtime-file (or data "")))
    (:tool (make-cell-tool (or data ""))) (:tree (make-cell-tree (or data "")))
    (:stat (make-cell-stat (or data ""))) (:env (make-cell-env (or data "")))
    (:argv (make-cell-argv)) (:config (make-cell-config (or data "")))
    (:handler (make-cell-handler (or data ""))) (:probe (make-cell-probe (or data "")))
    (:sealed (make-cell-sealed (or data ""))) (:node (make-cell-node (or data "")))
    (:domain (make-cell-domain (or name "") (or sub "")))
    (:unknown (make-cell-unknown (or data "")))))
(defun cell-kind (cell)
  (typecase cell
    (cell-file :file) (cell-runtime-file :runtime-file) (cell-tool :tool)
    (cell-tree :tree) (cell-stat :stat) (cell-env :env) (cell-argv :argv)
    (cell-config :config) (cell-handler :handler) (cell-probe :probe)
    (cell-sealed :sealed) (cell-node :node) (cell-domain :domain) (cell-unknown :unknown)))
(defun cell-data (cell)
  (typecase cell
    (cell-file (cell-file-value cell)) (cell-runtime-file (cell-runtime-file-value cell))
    (cell-tool (cell-tool-value cell)) (cell-tree (cell-tree-value cell))
    (cell-stat (cell-stat-value cell)) (cell-env (cell-env-value cell))
    (cell-config (cell-config-value cell)) (cell-handler (cell-handler-value cell))
    (cell-probe (cell-probe-value cell)) (cell-sealed (cell-sealed-value cell))
    (cell-node (cell-node-value cell)) (cell-unknown (cell-unknown-value cell))
    (cell-domain (cons (cell-domain-name cell) (cell-domain-sub cell)))
    (cell-argv nil)))

(defun cell-serialize (cell)
  (typecase cell
    (cell-file (concatenate 'string "file:" (cell-file-value cell)))
    (cell-runtime-file (concatenate 'string "runtime:file:" (cell-runtime-file-value cell)))
    (cell-tool (concatenate 'string "tool:" (cell-tool-value cell)))
    (cell-tree (concatenate 'string "tree:" (cell-tree-value cell)))
    (cell-stat (concatenate 'string "stat:" (cell-stat-value cell)))
    (cell-env (concatenate 'string "env:" (cell-env-value cell)))
    (cell-argv "argv:")
    (cell-config (concatenate 'string "config:" (cell-config-value cell)))
    (cell-handler (concatenate 'string "handler:" (cell-handler-value cell)))
    (cell-probe (concatenate 'string "probe:" (cell-probe-value cell)))
    (cell-sealed (concatenate 'string "sealed:" (cell-sealed-value cell)))
    (cell-node (concatenate 'string "node:" (cell-node-value cell)))
    (cell-domain (format nil "domain:~A:~A" (cell-domain-name cell) (cell-domain-sub cell)))
    (cell-unknown (cell-unknown-value cell))
    (t (error "Not an observation cell"))))

(defun has-prefix-p (prefix string)
  (and (<= (length prefix) (length string))
       (string= prefix string :end2 (length prefix))))
(defun cell-payload (prefix string) (subseq string (length prefix)))
(defun cell-parse (string)
  (cond
    ((has-prefix-p "runtime:file:" string) (make-cell-runtime-file (cell-payload "runtime:file:" string)))
    ((has-prefix-p "file:" string) (make-cell-file (cell-payload "file:" string)))
    ((has-prefix-p "tool:" string) (make-cell-tool (cell-payload "tool:" string)))
    ((has-prefix-p "tree:" string) (make-cell-tree (cell-payload "tree:" string)))
    ((has-prefix-p "stat:" string) (make-cell-stat (cell-payload "stat:" string)))
    ((has-prefix-p "env:" string) (make-cell-env (cell-payload "env:" string)))
    ((has-prefix-p "config:" string) (make-cell-config (cell-payload "config:" string)))
    ((has-prefix-p "handler:" string) (make-cell-handler (cell-payload "handler:" string)))
    ((has-prefix-p "probe:" string) (make-cell-probe (cell-payload "probe:" string)))
    ((has-prefix-p "sealed:" string) (make-cell-sealed (cell-payload "sealed:" string)))
    ((has-prefix-p "node:" string) (make-cell-node (cell-payload "node:" string)))
    ((has-prefix-p "domain:" string)
     (let* ((payload (cell-payload "domain:" string))
            (at (cl:position #\: payload)))
       (if at (make-cell-domain (subseq payload 0 at) (subseq payload (1+ at)))
           (make-cell-domain payload ""))))
    ((string= string "argv:") (make-cell-argv))
    (t (make-cell-unknown string))))
(defun serialize-cell (cell) (cell-serialize cell))
(defun parse-cell (string) (cell-parse string))
