(in-package :pp.kernel)

(defun quote-string (string)
  (check-type string string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across string
          for code = (char-code c)
          do (cond ((char= c #\\) (write-string "\\\\" out))
                   ((char= c #\") (write-string "\\\"" out))
                   ((or (< code #x20) (= code #x7f))
                    (write-string "\\x" out)
                    (write-char (char "0123456789abcdef" (ash code -4)) out)
                    (write-char (char "0123456789abcdef" (logand code #xf)) out))
                   (t (write-char c out))))
    (write-char #\" out)))

(defun parse-quoted-string (string start)
  (when (and (< start (length string)) (char= (char string start) #\"))
    (let ((out (make-string-output-stream)))
      (do ((i (1+ start) (1+ i)))
          ((>= i (length string)) nil)
        (let ((c (char string i)))
          (cond
            ((char= c #\")
             (return-from parse-quoted-string
               (values (get-output-stream-string out) (1+ i))))
            ((char= c #\\)
             (when (>= (1+ i) (length string))
               (return-from parse-quoted-string nil))
             (let ((next (char string (1+ i))))
               (cond
                 ((char= next #\\) (write-char #\\ out) (incf i))
                 ((char= next #\") (write-char #\" out) (incf i))
                 ((char= next #\x)
                  (when (> (+ i 3) (1- (length string)))
                    (return-from parse-quoted-string nil))
                  (let ((digits (subseq string (+ i 2) (+ i 4))))
                    (unless (every (lambda (x) (digit-char-p x 16)) digits)
                      (return-from parse-quoted-string nil))
                    (write-char (code-char (parse-integer digits :radix 16)) out)
                    (incf i 3)))
                 (t (return-from parse-quoted-string nil)))))
            (t (write-char c out))))))))
(defun decode-hex-float (token)
  (cond ((string= token "nan") (float-nan))
        ((string= token "inf") (float-positive-infinity))
        ((string= token "-inf") (float-negative-infinity))
        (t
         (handler-case
             (let* ((negative (and (> (length token) 0)
                                    (char= (char token 0) #\-)))
                    (start (if negative 1 0)))
               (unless (and (< (+ start 2) (length token))
                            (string= token "0x" :start1 start :end1 (+ start 2)))
                 (error "not hex float"))
               (let* ((p (cl:position #\p token :start (+ start 2)))
                      (mantissa-end (or p (error "missing exponent")))
                      (mantissa (subseq token (+ start 2) mantissa-end))
                      (exponent-text (subseq token (1+ p)))
                      (exponent (parse-integer exponent-text :radix 10
                                               :junk-allowed nil))
                      (dot (cl:position #\. mantissa))
                      (digits (if dot
                                  (concatenate 'string (subseq mantissa 0 dot)
                                               (subseq mantissa (1+ dot)))
                                  mantissa))
                      (fraction-digits (if dot
                                           (- (length mantissa) (1+ dot))
                                           0)))
                 (when (or (zerop (length digits))
                           (> (length digits) 256)
                           (> exponent 2000)
                           (< exponent -2000)
                           (not (every (lambda (x) (digit-char-p x 16)) digits)))
                   (error "invalid hex float"))
                 (let ((integer (parse-integer digits :radix 16)))
                   (if (zerop integer)
                       (if negative (- 0.0d0) 0.0d0)
                       (coerce (if negative
                                   (- (* integer
                                         (expt 16 (- fraction-digits))
                                         (expt 2 exponent)))
                                   (* integer
                                      (expt 16 (- fraction-digits))
                                      (expt 2 exponent)))
                               'double-float)))))
           (error () nil)))))

(defun codec-float-nan ()
  #+sbcl (sb-kernel:make-double-float #x7ff80000 0)
  #-sbcl (handler-case (/ 0.0d0 0.0d0) (error () nil)))
(defun float-nan () (codec-float-nan))
(defun float-positive-infinity ()
  #+sbcl (sb-kernel:make-double-float #x7ff00000 0)
  #-sbcl (handler-case (/ most-positive-double-float 0.0d0)
           (error () nil)))
(defun float-negative-infinity ()
  #+sbcl (sb-kernel:make-double-float -1048576 0)
  #-sbcl (- (float-positive-infinity)))

(defun codec-wrap (tag parts)
  (if parts (format nil "(~A ~{~A~^ ~})" tag parts) (format nil "(~A)" tag)))
(defun encode-value (value)
  (labels ((enc (v)
             (typecase v
               (value-nil "nil")
               (value-bool (if (value-bool-value v) "#t" "#f"))
               (value-int (codec-wrap "i" (list (canonical-integer-string (value-int-value v)))))
               (value-float (codec-wrap "f" (list (canonical-float-string (value-float-value v)))))
               (value-string (codec-wrap "s" (list (quote-string (value-string-value v)))))
               (value-keyword (codec-wrap "k" (list (quote-string (value-keyword-value v)))))
               (value-symbol (codec-wrap "y" (list (quote-string (value-symbol-value v)))))
               (value-pair (let ((a (enc (value-pair-car v))) (d (enc (value-pair-cdr v))))
                             (and a d (codec-wrap "p" (list a d)))))
               (value-vector (let ((parts (map 'list #'enc (value-vector-values v))))
                               (and (every #'identity parts) (codec-wrap "v" parts))))
               (value-map
                (let ((parts nil))
                  (dolist (entry (canonical-map-entries (value-map-entries v)))
                    (let ((k (enc (car entry))) (val (enc (cdr entry))))
                      (unless (and k val) (return-from enc nil))
                      (push (format nil "(~A ~A)" k val) parts)))
                  (codec-wrap "m" (nreverse parts))))
               (value-set (let ((parts (mapcar #'enc (canonical-set-elements (value-set-values v)))))
                            (and (every #'identity parts) (codec-wrap "t" parts))))
               ;; Code, capabilities, environments, thunks and sealed bytes
               ;; never enter durable data.
               ((or value-closure value-builtin value-capability value-thunk value-env-map value-sealed) nil)
               (t nil))))
    (enc value)))

(defun codec-expect-space (s i)
  (and (< i (length s))
       (char= (char s i) #\Space)
       (1+ i)))

(defun codec-read-until-close (s i)
  (let ((close (cl:position #\) s :start i)))
    (and close
         (values (subseq s i close) (1+ close)))))

(defun codec-parse-number (s pos tag)
  (let ((space (codec-expect-space s pos)))
    (if (not space)
        (values nil pos nil)
        (multiple-value-bind (token next)
            (codec-read-until-close s space)
          (if (not token)
              (values nil space nil)
              (if (and (char= tag #\i)
                       (find-if (lambda (c)
                                  (member c '(#\Space #\Tab #\Newline #\Return)))
                                token))
                  (values nil next nil)
                  (if (char= tag #\i)
                      (handler-case
                          (values (make-vint
                                   (parse-integer token :radix 10
                                                  :junk-allowed nil))
                                  next t)
                        (error () (values nil next nil)))
                      (let ((float (decode-hex-float token)))
                        (if float
                            (values (make-vfloat float) next t)
                            (values nil next nil))))))))))

(defun codec-parse-quoted-ctor (s pos tag)
  (let ((space (codec-expect-space s pos)))
    (if (not space)
        (values nil pos nil)
        (multiple-value-bind (text next)
            (parse-quoted-string s space)
          (if (and text (< next (length s))
                   (char= (char s next) #\)))
              (values (cond ((char= tag #\s) (make-vstring text))
                            ((char= tag #\k) (make-vkeyword text))
                            (t (make-vsymbol text)))
                      (1+ next) t)
              (values nil next nil))))))

(defun codec-parse-pair (s pos)
  (let ((space (codec-expect-space s pos)))
    (if (not space)
        (values nil pos nil)
        (multiple-value-bind (car p1 ok1)
            (codec-parse-value s space)
          (if (not ok1)
              (values nil p1 nil)
              (let ((space2 (codec-expect-space s p1)))
                (if (not space2)
                    (values nil p1 nil)
                    (multiple-value-bind (cdr p2 ok2)
                        (codec-parse-value s space2)
                      (if (and ok2 (< p2 (length s))
                               (char= (char s p2) #\)))
                          (values (make-vpair car cdr) (1+ p2) t)
                          (values nil p2 nil))))))))))

(defun codec-parse-map-entry (s pos)
  (if (or (>= pos (length s))
          (not (char= (char s pos) (code-char 40))))
      (values nil pos nil)
      (multiple-value-bind (key p1 ok1)
          (codec-parse-value s (1+ pos))
        (if (not ok1)
            (values nil p1 nil)
            (let ((space (codec-expect-space s p1)))
              (if (not space)
                  (values nil p1 nil)
                  (multiple-value-bind (value p2 ok2)
                      (codec-parse-value s space)
                    (if (and ok2 (< p2 (length s))
                             (char= (char s p2) #\)))
                        (values (cons (cons key value) nil) (1+ p2) t)
                        (values nil p2 nil)))))))))

(defun codec-parse-sequence (s pos tag items)
  (cond
    ((>= pos (length s)) (values nil pos nil))
    ((char= (char s pos) #\))
     (values (if (string= tag "v")
                 (make-vvector (coerce (nreverse items) 'vector))
                 (make-vset (canonical-set-elements (nreverse items))))
             (1+ pos) t))
    ((char= (char s pos) #\Space)
     (multiple-value-bind (item next ok)
         (codec-parse-value s (1+ pos))
       (if ok
           (codec-parse-sequence s next tag (cons item items))
           (values nil next nil))))
    (t (values nil pos nil))))

(defun codec-parse-map (s pos items)
  (cond
    ((>= pos (length s)) (values nil pos nil))
    ((char= (char s pos) #\))
     (values (make-vmap (canonical-map-entries (nreverse items)))
             (1+ pos) t))
    ((char= (char s pos) #\Space)
     (multiple-value-bind (entry next ok)
         (codec-parse-map-entry s (1+ pos))
       (if ok
           (codec-parse-map s next (cons (car entry) items))
           (values nil next nil))))
    (t (values nil pos nil))))

(defun codec-parse-compound (s i)
  (if (>= (1+ i) (length s))
      (values nil (1+ i) nil)
      (let ((tag (char s (1+ i)))
            (pos (+ i 2)))
        (cond
          ((or (char= tag #\i) (char= tag #\f))
           (codec-parse-number s pos tag))
          ((or (char= tag #\s) (char= tag #\k) (char= tag #\y))
           (codec-parse-quoted-ctor s pos tag))
          ((char= tag #\p) (codec-parse-pair s pos))
          ((or (char= tag #\v) (char= tag #\t))
           (codec-parse-sequence s pos (string tag) nil))
          ((char= tag #\m) (codec-parse-map s pos nil))
          (t (values nil pos nil))))))

(defun codec-parse-value (s i)
  (cond
    ((>= i (length s)) (values nil i nil))
    ((char= (char s i) #\()
     (codec-parse-compound s i))
    ((and (<= (+ i 3) (length s))
           (string= s "nil" :start1 i :end1 (+ i 3)))
     (values (make-vnil) (+ i 3) t))
    ((and (<= (+ i 2) (length s))
           (string= s "#t" :start1 i :end1 (+ i 2)))
     (values (make-vbool t) (+ i 2) t))
    ((and (<= (+ i 2) (length s))
           (string= s "#f" :start1 i :end1 (+ i 2)))
     (values (make-vbool nil) (+ i 2) t))
    (t (values nil i nil))))

(defun decode-value (string)
  (multiple-value-bind (value pos ok) (codec-parse-value string 0)
    (and ok (= pos (length string)) value)))
