(in-package :pp.kernel)

;;; Explicit tagged structures represent the pp AST and runtime values. User
;;; names are strings and no host reader symbols are used, which keeps values
;;; safe to encode later.
(defstruct (env (:constructor make-env (bindings &key (env-id 0) (env-hash ""))))
  (env-id 0 :type integer)
  (env-hash "" :type string)
  (bindings nil :type list))

(defstruct (pattern-literal (:constructor make-pliteral (value))) value)
(defstruct (pattern-variable (:constructor make-pvariable (name)))
  (name "" :type string))
(defstruct (pattern-wildcard (:constructor make-pwildcard ())))
(defstruct (pattern-list (:constructor make-plist (patterns &optional rest)))
  (patterns nil :type list) rest)
(defstruct (pattern-tagged (:constructor make-ptagged (tag patterns)))
  (tag "" :type string) (patterns nil :type list))

(defstruct (expr-literal (:constructor make-eliteral (value))) value)
(defstruct (expr-symbol (:constructor make-esymbol (name)))
  (name "" :type string))
(defstruct (expr-if (:constructor make-eif (condition then else))) condition then else)
(defstruct (expr-let (:constructor make-elet (bindings body)))
  (bindings nil :type list) body)
(defstruct (expr-fn (:constructor make-efn (params body)))
  (params nil :type list) body)
(defstruct (expr-apply (:constructor make-eapply (function arguments)))
  function (arguments nil :type list))
(defstruct (expr-quote (:constructor make-equote (expression))) expression)
(defstruct (expr-force (:constructor make-eforce (expression))) expression)
(defstruct (expr-with-caps (:constructor make-ewith-caps (caps body))) caps body)
(defstruct (expr-perform (:constructor make-eperform (name arguments)))
  (name "" :type string) (arguments nil :type list))
(defstruct (expr-with-handler (:constructor make-ewith-handler (handlers body)))
  (handlers nil :type list) body)
(defstruct (expr-delay (:constructor make-edelay (expression))) expression)
(defstruct (expr-node (:constructor make-enode (expression))) expression)
(defstruct (expr-defnode (:constructor make-edefnode (name params body)))
  (name "" :type string) (params nil :type list) body)
(defstruct (expr-do (:constructor make-edo (expressions)))
  (expressions nil :type list))
(defstruct (expr-def (:constructor make-edef (name params body)))
  (name "" :type string) (params nil :type list) body)
(defstruct (expr-defvalue (:constructor make-edefvalue (name expression)))
  (name "" :type string) expression)
(defstruct (expr-letstar (:constructor make-eletstar (bindings body)))
  (bindings nil :type list) body)
(defstruct (expr-module (:constructor make-emodule (expressions)))
  (expressions nil :type list))
(defstruct (expr-import (:constructor make-eimport (expression))) expression)
(defstruct (expr-load (:constructor make-eload (path))) (path "" :type string))
(defstruct (expr-loadmodule (:constructor make-eloadmodule (path))) (path "" :type string))
(defstruct (expr-island (:constructor make-eisland (uri &optional pin)))
  (uri "" :type string) pin)
(defstruct (expr-with-config (:constructor make-ewith-config (map-expression body)))
  map-expression body)
(defstruct (expr-config (:constructor make-econfig (key-expression &optional default)))
  key-expression default)
(defstruct (expr-typed (:constructor make-typed (expression type))) expression type)
(defstruct (expr-located (:constructor make-elocated (range expression))) range expression)
(defstruct (expr-match (:constructor make-ematch (scrutinee arms))) scrutinee (arms nil :type list))

(defstruct (closure-kind-function (:constructor make-closure-kind-function ())))
(defstruct (closure-kind-node (:constructor make-closure-kind-node ())))

(defstruct (closure (:constructor %make-closure
                                  (params body env &key fn-name closure-kind)))
  fn-name (params nil :type list) body (env (make-env nil)) closure-kind)

(defun make-closure (params body env &key fn-name (closure-kind :function))
  (let ((kind (cond ((or (null closure-kind) (eq closure-kind :function))
                     (make-closure-kind-function))
                    ((eq closure-kind :node) (make-closure-kind-node))
                    ((or (typep closure-kind 'closure-kind-function)
                         (typep closure-kind 'closure-kind-node))
                     closure-kind)
                    (t (error "Invalid closure kind ~S" closure-kind)))))
    (%make-closure params body env :fn-name fn-name :closure-kind kind)))

(defstruct (thunk-kind-ephemeral (:constructor make-ephemeral-thunk-kind ())))
(defstruct (thunk-kind-persistent
            (:constructor make-persistent-thunk-kind (captured-caps argument-values)))
  (captured-caps nil :type list) (argument-values nil :type list))

(defstruct (thunk-status-unevaluated (:constructor make-thunk-status-unevaluated ())))
(defstruct (thunk-status-evaluating (:constructor make-thunk-status-evaluating ())))
(defstruct (thunk-status-evaluated (:constructor make-thunk-status-evaluated (value)))
  value)

(defstruct (thunk (:constructor %make-thunk
                               (expression environment
                                &key status hash name type-ann location config-hash kind)))
  status hash expression (environment (make-env nil)) name type-ann location
  (config-hash "") kind)

(defun make-thunk (expression environment
                   &key status hash name type-ann location config-hash kind)
  (let ((normalized-status
          (cond ((or (null status) (eq status :unevaluated))
                 (make-thunk-status-unevaluated))
                ((eq status :evaluating) (make-thunk-status-evaluating))
                ((eq status :evaluated)
                 (error "Evaluated thunk status requires a value"))
                ((or (typep status 'thunk-status-unevaluated)
                     (typep status 'thunk-status-evaluating)
                     (typep status 'thunk-status-evaluated))
                 status)
                ((and (consp status) (eq (car status) :evaluated)
                      (cdr status))
                 (make-thunk-status-evaluated (cadr status)))
                (t (error "Invalid thunk status ~S" status))))
        (normalized-kind
          (cond ((or (null kind) (eq kind :ephemeral))
                 (make-ephemeral-thunk-kind))
                ((eq kind :persistent)
                 (make-persistent-thunk-kind nil nil))
                ((or (typep kind 'thunk-kind-ephemeral)
                     (typep kind 'thunk-kind-persistent))

                 kind)
                (t (error "Invalid thunk kind ~S" kind)))))
    (%make-thunk expression environment :status normalized-status :hash hash
                 :name name :type-ann type-ann :location location
                 :config-hash config-hash :kind normalized-kind)))
(defstruct (value-nil (:constructor make-vnil ())))
(defstruct (value-bool (:constructor make-vbool (value))) value)
(defstruct (value-int (:constructor %make-vint (value)))
  (value 0 :type integer))
(defstruct (value-float (:constructor make-vfloat (value))) value)

(defconstant +vint-max+ (1- (ash 1 62)))
(defconstant +vint-min+ (- (ash 1 62)))
(defun make-vint (value)
  (check-type value integer)
  (if (<= +vint-min+ value +vint-max+)
      (%make-vint value)
      (error "VInt out of signed 63-bit range: ~D" value)))
(defstruct (value-string (:constructor make-vstring (value))) (value "" :type string))
(defstruct (value-keyword (:constructor make-vkeyword (value))) (value "" :type string))
(defstruct (value-symbol (:constructor make-vsymbol (value))) (value "" :type string))
(defstruct (value-pair (:constructor make-vpair (car cdr))) car cdr)
(defstruct (value-vector (:constructor make-vvector (values)))
  (values #() :type vector))
(defstruct (value-map (:constructor make-vmap (entries)))
  (entries nil :type list))
(defstruct (value-set (:constructor make-vset (values)))
  (values nil :type list))
(defstruct (value-closure (:constructor make-vclosure (closure))) closure)
(defstruct (value-builtin (:constructor make-vbuiltin (name &optional implementation)))
  (name "" :type string) implementation)
(defstruct (value-capability (:constructor make-vcapability (capability))) capability)
(defstruct (value-thunk (:constructor make-vthunk (thunk))) thunk)
(defstruct (value-env-map (:constructor make-venvmap (bindings)))
  (bindings nil :type list))
(defstruct (value-sealed (:constructor make-vsealed (bytes))) (bytes "" :type string))

(defun make-vvector-from-list (values) (make-vvector (coerce values 'vector)))
(defun make-vpersistent-thunk-kind (captured-caps argument-values)
  (make-persistent-thunk-kind captured-caps argument-values))
