(in-package :pp.kernel)

(defun canonical-float-nan-p (f)
  #+sbcl (sb-ext:float-nan-p f)
  #-sbcl (handler-case (not (= f f)) (error () t)))

(defun canonical-float-string (number)
  "Return a shortest exact hexadecimal spelling for NUMBER."
  (let ((f (coerce number 'double-float)))
    (cond
      ((canonical-float-nan-p f) "nan")
      ((> f most-positive-double-float) "inf")
      ((< f (- most-positive-double-float)) "-inf")
      ((zerop f) (if (minusp (float-sign f)) "-0x0p+0" "0x0p+0"))
      (t
       (multiple-value-bind (mantissa exponent sign) (integer-decode-float f)
         (let* ((m (abs mantissa))
                (high (1- (integer-length m)))
                (subnormal (< high 52))
                ;; [%h] keeps those in the 0x0.*p-1022 form.
                (fraction (if subnormal
                              m
                              (- m (ash 1 52))))
                (binary-exponent (if subnormal -1022 (+ exponent high)))
                (digits (if (zerop fraction)
                            ""
                            (let ((text (make-string 13 :initial-element #\0)))
                              (loop for i from 0 below 13
                                    do (setf (char text i)
                                             (char "0123456789abcdef"
                                                   (ldb (byte 4 (* (- 12 i) 4))
                                                        fraction))))
                              (loop while (and (> (length text) 0)
                                               (char= (char text (1- (length text)))
                                                      #\0))
                                    do (setf text (subseq text 0 (1- (length text)))))
                              text))))
           (concatenate 'string
                        (if (minusp sign) "-" "")
                        (if subnormal "0x0" "0x1")
                        (if (plusp (length digits))
                            (concatenate 'string "." digits) "")
                        "p"
                        (if (>= binary-exponent 0) "+" "")
                        (canonical-integer-string binary-exponent))))))))

(defun name-member-p (name names) (member name names :test #'string=))
(defun name-union (a b)
  (reduce (lambda (out x) (if (name-member-p x out) out (cons x out)))
          b :initial-value a))
(defun name-minus (names bound)
  (remove-if (lambda (name) (name-member-p name bound)) names))
(defun pattern-bound-names (pattern)
  (typecase pattern
    (pattern-variable (list (pattern-variable-name pattern)))
    (pattern-list (name-union
                   (reduce (lambda (out p) (name-union out (pattern-bound-names p)))
                           (pattern-list-patterns pattern) :initial-value nil)
                   (if (pattern-list-rest pattern)
                       (pattern-bound-names (pattern-list-rest pattern)) nil)))
    (pattern-tagged (reduce (lambda (out p) (name-union out (pattern-bound-names p)))
                            (pattern-tagged-patterns pattern) :initial-value nil))
    (t nil)))

(defun free-variable-names (expression)
  (labels ((block-binders (forms)
             (remove nil (mapcar (lambda (e)
                                   (typecase e
                                     (expr-def (expr-def-name e))
                                     (expr-defnode (expr-defnode-name e))
                                     (expr-defvalue (expr-defvalue-name e))
                                     (expr-located (block-binders (list (expr-located-expression e))))
                                     (t nil))) forms)))
           (fv (bound e)
             (typecase e
               (expr-literal nil) (expr-quote nil) (expr-load nil)
               (expr-loadmodule nil) (expr-island nil)
               (expr-symbol (if (name-member-p (expr-symbol-name e) bound)
                                nil (list (expr-symbol-name e))))
               (expr-if (name-union (fv bound (expr-if-condition e))
                                    (name-union (fv bound (expr-if-then e))
                                                (fv bound (expr-if-else e)))))
               (expr-let
                (let* ((bindings (expr-let-bindings e))
                       (names (mapcar #'car bindings))
                       (bound2 (name-union bound names)))
                  (reduce (lambda (out b) (name-union out (fv bound2 (cdr b))))
                          bindings :initial-value (fv bound2 (expr-let-body e)))))
               (expr-letstar
                (labels ((walk (bs current)
                           (if (null bs) (fv current (expr-letstar-body e))
                               (name-union (fv current (cdar bs))
                                           (walk (cdr bs) (cons (caar bs) current))))))
                  (walk (expr-letstar-bindings e) bound)))
               (expr-fn (fv (name-union bound (expr-fn-params e)) (expr-fn-body e)))
               (expr-apply (reduce (lambda (out x) (name-union out (fv bound x)))
                                   (expr-apply-arguments e)
                                   :initial-value (fv bound (expr-apply-function e))))
               (expr-quote nil)
               (expr-force (fv bound (expr-force-expression e)))
               (expr-with-caps (name-union (fv bound (expr-with-caps-caps e))
                                           (fv bound (expr-with-caps-body e))))
               (expr-perform (reduce (lambda (out x) (name-union out (fv bound x)))
                                     (expr-perform-arguments e) :initial-value nil))
               (expr-with-handler
                (reduce (lambda (out h) (name-union out (fv bound (cdr h))))
                        (expr-with-handler-handlers e)
                        :initial-value (fv bound (expr-with-handler-body e))))
               (expr-delay (fv bound (expr-delay-expression e)))
               (expr-node (fv bound (expr-node-expression e)))
               ((or expr-def expr-defnode)
                (let ((name (if (typep e 'expr-def) (expr-def-name e) (expr-defnode-name e)))
                      (params (if (typep e 'expr-def) (expr-def-params e) (expr-defnode-params e)))
                      (body (if (typep e 'expr-def) (expr-def-body e) (expr-defnode-body e))))
                  (fv (name-union (cons name bound) params) body)))
               (expr-defvalue (fv bound (expr-defvalue-expression e)))
               ((or expr-do expr-module)
                (let* ((forms (if (typep e 'expr-do) (expr-do-expressions e)
                                  (expr-module-expressions e)))
                       (bound2 (name-union bound (block-binders forms))))
                  (reduce (lambda (out x) (name-union out (fv bound2 x))) forms
                          :initial-value nil)))
               (expr-import (fv bound (expr-import-expression e)))
               (expr-with-config (name-union (fv bound (expr-with-config-map-expression e))
                                             (fv bound (expr-with-config-body e))))
               (expr-config (name-union (fv bound (expr-config-key-expression e))
                                        (if (expr-config-default e)
                                            (fv bound (expr-config-default e)) nil)))
               (expr-typed (fv bound (expr-typed-expression e)))
               (expr-located (fv bound (expr-located-expression e)))
               (expr-match
                (name-union (fv bound (expr-match-scrutinee e))
                            (reduce (lambda (out arm)
                                      (destructuring-bind (pattern guard body) arm
                                        (let ((b (name-union bound (pattern-bound-names pattern))))
                                          (name-union out (name-union (if guard (fv b guard) nil)
                                                                        (fv b body))))))
                                    (expr-match-arms e) :initial-value nil)))
               (t nil))))
    (sort (copy-seq (fv nil expression)) #'string<)))

(defun hash-expr (expression)
  (labels ((h (e)
             (typecase e
               (expr-literal (hash-concat (list "lit" (hash-value (expr-literal-value e)))))
               (expr-symbol (hash-concat (list "sym" (expr-symbol-name e))))
               (expr-if (hash-concat (list "if" (h (expr-if-condition e))
                                          (h (expr-if-then e)) (h (expr-if-else e)))))
               (expr-let (hash-concat (append (list "let")
                                              (mapcar (lambda (b) (hash-concat (list "let_bind" (car b) (h (cdr b)))))
                                                      (sort (copy-list (expr-let-bindings e)) #'string< :key #'car))
                                              (list (h (expr-let-body e))))))
               (expr-fn (hash-concat (list "fn" (hash-concat (cons "params" (expr-fn-params e)))
                                     (h (expr-fn-body e)))))
               (expr-apply (hash-concat (cons "apply" (cons (h (expr-apply-function e))
                                                             (mapcar #'h (expr-apply-arguments e))))))
               (expr-quote (hash-concat (list "quote" (h (expr-quote-expression e)))))
               (expr-force (hash-concat (list "force" (h (expr-force-expression e)))))
               (expr-with-caps (hash-concat (list "with_caps" (h (expr-with-caps-caps e))
                                                  (h (expr-with-caps-body e)))))
               (expr-perform (hash-concat (cons "perform" (cons (expr-perform-name e)
                                                                  (mapcar #'h (expr-perform-arguments e))))))
               (expr-with-handler (hash-concat
                                   (append (list "with_handler")
                                           (mapcar (lambda (x) (hash-concat (list "handler" (car x) (h (cdr x)))))
                                                   (expr-with-handler-handlers e))
                                           (list (h (expr-with-handler-body e))))))
               (expr-delay (hash-concat (list "delay" (h (expr-delay-expression e)))))
               (expr-node (hash-concat (list "node" (h (expr-node-expression e)))))
               (expr-defnode (hash-concat (list "defnode" (expr-defnode-name e)
                                                (hash-concat (cons "params" (expr-defnode-params e)))
                                                (h (expr-defnode-body e)))))
               (expr-do (hash-concat (cons "do" (mapcar #'h (expr-do-expressions e)))))
               (expr-def (hash-concat (list "def" (expr-def-name e)
                                            (hash-concat (cons "params" (expr-def-params e)))
                                            (h (expr-def-body e)))))
               (expr-defvalue (hash-concat (list "def-value" (expr-defvalue-name e)
                                                 (h (expr-defvalue-expression e)))))
               (expr-letstar (hash-concat (append (list "let_star")
                                                  (mapcar (lambda (b) (hash-concat (list "let_star_bind" (car b) (h (cdr b)))))
                                                          (expr-letstar-bindings e))
                                                  (list (h (expr-letstar-body e))))))
               (expr-module (hash-concat (cons "module" (mapcar #'h (expr-module-expressions e)))))
               (expr-import (hash-concat (list "import" (h (expr-import-expression e)))))
               (expr-load (hash-concat (list "load" (expr-load-path e))))
               (expr-loadmodule (hash-concat (list "load_module" (expr-loadmodule-path e))))
               (expr-island (hash-concat (list "island" (expr-island-uri e)
                                                (if (expr-island-pin e)
                                                    (hash-concat (list "pin" (expr-island-pin e))) "nopin"))))
               (expr-with-config (hash-concat (list "with_config" (h (expr-with-config-map-expression e))
                                                    (h (expr-with-config-body e)))))
               (expr-config (hash-concat (list "config" (h (expr-config-key-expression e))
                                               (if (expr-config-default e) (h (expr-config-default e)) ""))))
               (expr-typed (hash-concat (list "typed" (h (expr-typed-expression e))
                                              (h (expr-typed-type e)))))
               (expr-located (let ((p (source-range-start (expr-located-range e))))
                               (hash-concat (list "located" (source-range-source (expr-located-range e))
                                                  (canonical-integer-string (position-line p)) (h (expr-located-expression e))))))
               (expr-match (hash-concat (cons "match" (cons (h (expr-match-scrutinee e))
                                                              (mapcar (lambda (arm)
                                                                        (destructuring-bind (p g b) arm
                                                                          (if g (hash-concat (list "arm-guard" (hash-pattern p) (h g) (h b)))
                                                                              (hash-concat (list "arm" (hash-pattern p) (h b))))))
                                                                      (expr-match-arms e))))))
               (t (error "Unknown expression structure")))))
    (h expression)))

(defun hash-pattern (pattern)
  (typecase pattern
    (pattern-literal (hash-concat (list "p_lit" (hash-value (pattern-literal-value pattern)))))
    (pattern-variable (hash-concat (list "p_var" (pattern-variable-name pattern))))
    (pattern-wildcard "p_wild")
    (pattern-list (hash-concat (list "p_list"
                                     (hash-concat (mapcar #'hash-pattern (pattern-list-patterns pattern)))
                                     (if (pattern-list-rest pattern) (hash-pattern (pattern-list-rest pattern)) "nil"))))
    (pattern-tagged (hash-concat (list "p_tagged" (pattern-tagged-tag pattern)
                                       (hash-concat (mapcar #'hash-pattern (pattern-tagged-patterns pattern))))))
    (t (error "Unknown pattern structure"))))

(defun hash-value (value)
  (labels ((lookup (name bindings)
             (let ((entry (find name bindings :key #'car :test #'string=))) (and entry (cdr entry))))
           (capture-hash (active expression environment)
             (hash-concat
              (cons "captures"
                    (mapcar (lambda (name)
                              (let ((v (lookup name (env-bindings environment))))
                                (if v (hash-concat (list "capture" name (hv active v)))
                                    (hash-concat (list "capture-unbound" name)))))
                            (free-variable-names expression)))))
           (hv (active v)
             (let ((index (cl:position v active :test #'eq)))
               (if index (hash-concat (list "recursive-value" (canonical-integer-string index)))
                   (hf (cons v active) v))))
           (sorted-hashed-values (active values)
             (sort (copy-list values) #'string< :key (lambda (x) (hv active x))))
           (canonical-map-active (active entries)
             (let ((seen nil))
               (dolist (entry entries)
                 (let* ((key (car entry)) (kh (hv active key)) (old (assoc kh seen :test #'string=)))
                   (if old (setf (cdr old) entry) (push (cons kh entry) seen))))
               (sort seen #'string< :key #'car)))
           (hf (active v)
             (typecase v
               (value-nil (hash-string "nil"))
               (value-bool (hash-string (if (value-bool-value v) "bool:true" "bool:false")))
               (value-int (hash-concat (list "int" (canonical-integer-string (value-int-value v)))))
               (value-float (hash-concat (list "float" (canonical-float-string (value-float-value v)))))
               (value-string (hash-concat (list "string" (value-string-value v))))
               (value-keyword (hash-concat (list "keyword" (value-keyword-value v))))
               (value-symbol (hash-concat (list "symbol" (value-symbol-value v))))
               (value-pair (hash-concat (list "pair" (hv active (value-pair-car v))
                                              (hv active (value-pair-cdr v)))))
               (value-vector (hash-concat (cons "vector" (map 'list (lambda (x) (hv active x))
                                                               (value-vector-values v)))))
               (value-map
                (hash-concat
                 (cons "map"
                       (mapcar (lambda (item)
                                 (let ((key-hash (car item)) (entry (cdr item)))
                                   (hash-concat (list key-hash (hv active (cdr entry))))))
                               (canonical-map-active active (value-map-entries v))))))
               (value-set (hash-concat (cons "set"
                                             (mapcar (lambda (x) (hv active x))
                                                     (sorted-hashed-values active (value-set-values v))))))
               (value-closure
                (let* ((c (value-closure-closure v))
                       (kind (if (or (typep (closure-closure-kind c) 'closure-kind-node)
                                     (eq (closure-closure-kind c) :node))
                                 "node-closure" "closure")))
                  (hash-concat (list kind (or (closure-fn-name c) "anon")
                                     (hash-concat (cons "params" (closure-params c)))
                                     (hash-expr (closure-body c))
                                     (capture-hash active (closure-body c) (closure-env c))))))
               (value-builtin (hash-concat (list "builtin" (value-builtin-name v))))
               (value-capability (capability-hash (value-capability-capability v)))
               (value-thunk
                (let* ((thunk (value-thunk-thunk v))
                       (type-part (if (thunk-type-ann thunk)
                                      (hash-concat (list "type" (hash-expr (thunk-type-ann thunk)))) "untyped"))
                       (location-part (if (thunk-location thunk)
                                          (let ((p (source-range-start (thunk-location thunk))))
                                            (hash-concat (list "location" "some"
                                                               (source-range-source (thunk-location thunk))
                                                               (canonical-integer-string (position-line p)))))
                                          (hash-concat (list "location" "none"))))
                       (kind-parts (if (typep (thunk-kind thunk) 'thunk-kind-persistent)
                                       (cons "persistent"
                                             (mapcar (lambda (x) (hv active x))
                                                     (thunk-kind-persistent-argument-values (thunk-kind thunk))))
                                       (list "ephemeral"))))
                  (hash-concat (append (list "thunk" (hash-expr (thunk-expression thunk)) type-part location-part
                                             (thunk-config-hash thunk) (capture-hash active (thunk-expression thunk)
                                                                                  (thunk-environment thunk)))
                                       kind-parts))))
               (value-env-map (hash-concat
                               (cons "envmap"
                                     (mapcar (lambda (entry)
                                               (hash-concat (list (car entry) (hv active (cdr entry)))))
                                             (sort (copy-list (value-env-map-bindings v)) #'string< :key #'car)))))
               (value-sealed (hash-concat (list "sealed" (value-sealed-bytes v))))
               (t (error "Unknown value structure")))))
    (hv nil value)))

(defun canonical-map-entries (entries)
  (let ((seen nil))
    (dolist (entry entries)
      (let* ((key (car entry)) (kh (hash-value key)) (old (assoc kh seen :test #'string=)))
        (if old (setf (cdr old) entry) (push (cons kh entry) seen))))
    (mapcar #'cdr (sort seen #'string< :key #'car))))
(defun canonical-set-elements (values)
  (let ((seen nil))
    (dolist (value values)
      (let ((h (hash-value value)) (old (assoc (hash-value value) seen :test #'string=)))
        (unless old (push (cons h value) seen))))
    (mapcar #'cdr (sort seen #'string< :key #'car))))
(defun equal-value (a b) (string= (hash-value a) (hash-value b)))
(defun same-content (a b) (equal-value a b))

(defun node-key (&key code free-variables argument-values)
  (let ((fv (mapcar (lambda (entry)
                      (let ((name (car entry)) (value (cdr entry)))
                        (if value (hash-concat (list "fv" name (hash-value value)))
                            (hash-concat (list "fv-unbound" name)))))
                    free-variables))
        (args (mapcar (lambda (value) (hash-concat (list "arg" (hash-value value)))) argument-values)))
    (make-node-key (node-key-skeleton (hash-expr code) (append fv args)))))
