(in-package :pp.kernel)

;;; Text identities are represented by distinct structures rather than bare
;;; strings.  This prevents a node key from being accidentally passed where an
;;; object hash or observation/cell identifier is required.
(defstruct (node-key (:constructor %make-node-key (string)))
  (string "" :type string))
(defstruct (cache-key (:constructor %make-cache-key (string)))
  (string "" :type string))
(defstruct (object-hash (:constructor %make-object-hash (string)))
  (string "" :type string))
(defstruct (observed-hash (:constructor %make-observed-hash (string)))
  (string "" :type string))
(defstruct (cell-id (:constructor %make-cell-id (string)))
  (string "" :type string))

(defun make-node-key (string)
  (check-type string string)
  (%make-node-key string))
(defun node-key-of-string (string) (make-node-key string))
(defun node-key-to-string (key)
  (check-type key node-key)
  (node-key-string key))

(defun make-cache-key (string)
  (check-type string string)
  (%make-cache-key string))
(defun cache-key-of-string (string) (make-cache-key string))
(defun cache-key-from-node-key (key)
  (make-cache-key (node-key-to-string key)))
(defun cache-key-of-node-key (key) (cache-key-from-node-key key))
(defun cache-key-to-string (key)
  (check-type key cache-key)
  (cache-key-string key))

(defun make-object-hash (string)
  (check-type string string)
  (%make-object-hash string))
(defun object-hash-of-digest (string) (make-object-hash string))
(defun object-hash-to-string (hash)
  (check-type hash object-hash)
  (object-hash-string hash))

(defun make-observed-hash (string)
  (check-type string string)
  (%make-observed-hash string))
(defun observed-hash-of-digest (string) (make-observed-hash string))
(defun observed-hash-to-string (hash)
  (check-type hash observed-hash)
  (observed-hash-string hash))

(defun make-cell-id (string)
  (check-type string string)
  (%make-cell-id string))
(defun cell-id-of-string (string) (make-cell-id string))
(defun cell-id-to-string (id)
  (check-type id cell-id)
  (cell-id-string id))
