(in-package :pp.kernel)

(defstruct (position (:constructor %make-position (offset line column)))
  (offset 0 :type integer)
  (line 1 :type integer)
  (column 1 :type integer))

(defun make-position (&key (offset 0) (line 1) (column 1))
  (check-type offset integer)
  (check-type line integer)
  (check-type column integer)
  (%make-position offset line column))

(defstruct (source-range (:constructor %make-source-range (source start end)))
  (source "" :type string)
  (start (make-position) :type position)
  (end (make-position) :type position))

(defun make-source-range (&key source start-pos end-pos)
  (check-type source string)
  (check-type start-pos position)
  (check-type end-pos position)
  (when (> (position-offset start-pos) (position-offset end-pos))
    (error "Source range end precedes start"))
  (%make-source-range source start-pos end-pos))

(defun source-range-point (&key source offset line column)
  (let ((p (make-position :offset offset :line line :column column)))
    (make-source-range :source source :start-pos p :end-pos p)))

(defun compare-positions (a b)
  (or (and (= (position-offset a) (position-offset b))
           (or (and (= (position-line a) (position-line b))
                    (signum (- (position-column a) (position-column b))))
               (signum (- (position-line a) (position-line b)))))
      (signum (- (position-offset a) (position-offset b)))))
(defun source-range-equal (a b)
  (and (string= (source-range-source a) (source-range-source b))
       (= 0 (compare-positions (source-range-start a) (source-range-start b)))
       (= 0 (compare-positions (source-range-end a) (source-range-end b)))))
(defun source-range-empty-p (range)
  (= 0 (compare-positions (source-range-start range) (source-range-end range))))
(defun source-range-path (range) (source-range-source range))

(defun source-range-format-start (range)
  (format nil "~A:~D:~D" (source-range-source range)
          (position-line (source-range-start range))
          (position-column (source-range-start range))))
(defun source-range-format (range)
  (let ((p (source-range-start range)) (q (source-range-end range)))
    (if (and (= (position-line p) (position-line q))
             (= (position-column p) (position-column q)))
        (source-range-format-start range)
        (format nil "~A:~D:~D-~D:~D" (source-range-source range)
                (position-line p) (position-column p)
                (position-line q) (position-column q)))))
