(* pp fuzzer — generates random pp programs and checks them via a
   single-engine metamorphic + roundtrip oracle.

   Every generated program is pushed through `pp f` (the tree-walker),
   AND through `pp --roundtrip-braces f`, which (in one process)
   reads the sexpr AST, prints it as location-preserving brace text
   (src/printer_braces.ml), re-reads that with the brace reader
   MISMATCH (`roundtrip:*` signature), shrunk like any other.

   Metamorphic oracle: every generated program P is ALSO transformed into a
   twin T(P) by 1–3 semantics-preserving wraps (do, let-identity, or
   eta-identity) at random eligible positions, then P and T(P) are run
   through the SAME single backend (`pp f`) and compared. Any divergence is
   a single-engine bug.

   OCaml stdlib + unix only.  Build+run:  dune exec ./tools/fuzz.exe -- ARGS
   Fully deterministic given --seed: program i is generated from
   Random.full_init [| seed; i |], so any program can be regenerated with
   --seed S --start i --count 1 (or inspected with --dump i).

   Grammar notes (verified against src/primitives.ml, stdlib/list.pp, reader.ml):
   - builtins used: + - * / mod < > <= >= = not list cons car cdr nil? print
     string-append string-length string-trim string-sub string-index
     number->string string->number vector vector-get hash-map hash-map-get
   - stdlib fns (require (load ".../stdlib/list.pp")): map filter foldl range take length
   - `and`/`or` are reader-level special forms (desugar to if) — safe.
   - (def x 5) is a VALUE binding (evaluated at definition time, sequential
     at top level) — generated by stmt_def_value and referenced by later
     statements. Function defs still always take >= 1 parameter.
   - `let` is parallel (bindings see the OUTER env).
   - car/cdr of nil returns nil (no error); still, car is only applied to
     statically-nonempty lists so arithmetic on the element is well-typed.
   - / and mod only ever get a nonzero positive literal divisor.
   - No random / wall-clock / network-island forms are ever generated;
     pinned file: islands over a fixed fixture are sampled in `full`.
   - `defmacro`: `stmt_defmacro` (full only) defines a fresh,
     well-scoped macro that doubles its (always-literal) argument via
     `list`/`quote`, then calls it — exercises the shared expansion point
     (macro.ml). *)

(* ---------------------------------------------------------------- CLI ---- *)

let seed = ref 0
let count = ref 1000
let max_depth = ref 6
let timeout_ms = ref 5000
let out_dir = ref "fuzz-failures"
let grammar = ref "core"
let start_iter = ref 0
let dump_iter = ref (-1)
let pp_bin = ref "bin/pp"
let stdlib_path = ref ""   (* default computed from cwd *)
let shrink_budget = ref 300
let no_metamorphic = ref false

let usage () =
  prerr_endline "usage: fuzz [--seed N] [--count K] [--max-depth D] [--timeout-ms T]";
  prerr_endline "            [--out DIR] [--grammar core|full] [--start N] [--dump N]";
  prerr_endline "            [--pp PATH] [--stdlib PATH] [--shrink-budget N] [--no-metamorphic]";
  exit 2

let parse_cli () =
  let rec go = function
    | [] -> ()
    | "--seed" :: v :: r -> seed := int_of_string v; go r
    | "--count" :: v :: r -> count := int_of_string v; go r
    | "--max-depth" :: v :: r -> max_depth := int_of_string v; go r
    | "--timeout-ms" :: v :: r -> timeout_ms := int_of_string v; go r
    | "--out" :: v :: r -> out_dir := v; go r
    | "--grammar" :: v :: r ->
        if v <> "core" && v <> "full" then usage (); grammar := v; go r
    | "--start" :: v :: r -> start_iter := int_of_string v; go r
    | "--dump" :: v :: r -> dump_iter := int_of_string v; go r
    | "--pp" :: v :: r -> pp_bin := v; go r
    | "--stdlib" :: v :: r -> stdlib_path := v; go r
    | "--shrink-budget" :: v :: r -> shrink_budget := int_of_string v; go r
    | "--no-metamorphic" :: r -> no_metamorphic := true; go r
    | ("--help" | "-h") :: _ -> usage ()
    | x :: _ -> prerr_endline ("unknown argument: " ^ x); usage ()
  in
  go (List.tl (Array.to_list Sys.argv));
  if !stdlib_path = "" then
    stdlib_path := Filename.concat (Sys.getcwd ()) "stdlib/list.pp"

(* ------------------------------------------------------------- S-exprs -- *)

type sx =
  | A of string        (* atom, rendered verbatim *)
  | S of sx list       (* ( ... ) *)
  | V of sx list       (* [ ... ] *)
  | C of sx list       (* { ... } *)

let rec render_sx buf sx =
  match sx with
  | A s -> Buffer.add_string buf s
  | S xs -> Buffer.add_char buf '('; render_list buf xs; Buffer.add_char buf ')'
  | V xs -> Buffer.add_char buf '['; render_list buf xs; Buffer.add_char buf ']'
  | C xs -> Buffer.add_char buf '{'; render_list buf xs; Buffer.add_char buf '}'

and render_list buf = function
  | [] -> ()
  | [x] -> render_sx buf x
  | x :: rest -> render_sx buf x; Buffer.add_char buf ' '; render_list buf rest

let render_program (forms : sx list) : string =
  let buf = Buffer.create 512 in
  List.iter (fun f -> render_sx buf f; Buffer.add_char buf '\n') forms;
  Buffer.contents buf

(* ----------------------------------------------------------- Generator -- *)

type ty = TInt | TFloat | TBool | TStr | TList

type gvar = { vname : string; vty : ty; vne : bool }  (* vne: list known nonempty *)

type genv = {
  vars : gvar list;                  (* lexical, per-statement *)
  mutable fns : (string * int * bool) list;
                                     (* top-level int fns: name, arity, recursive.
                                        Args at call sites of RECURSIVE fns are
                                        wrapped in (mod _ 64): recursion depth
                                        stays bounded, so a one-sided timeout on
                                        a terminating-but-slow program (perf
                                        asymmetry, not semantics) cannot poison
                                        the ratchet. *)
  mutable stdlib : bool;             (* stdlib list.pp loaded *)
  mutable gvars : gvar list;         (* top-level (def x v) value bindings —
                                        sequential, so any later statement may
                                        reference them *)
}

let name_counter = ref 0
let fresh prefix = incr name_counter; Printf.sprintf "%s%d" prefix !name_counter

let rint lo hi = lo + Random.int (hi - lo + 1)
let flip p = Random.float 1.0 < p

(* weighted pick *)
let pick (choices : (int * (unit -> 'a)) list) : 'a =
  let total = List.fold_left (fun a (w, _) -> a + w) 0 choices in
  let n = Random.int total in
  let rec go acc = function
    | [] -> assert false
    | (w, f) :: rest -> if n < acc + w then f () else go (acc + w) rest
  in
  go 0 choices

let str_pool = [| "a"; "bc"; "xyz"; "hello"; "pp"; "zz"; "q0"; "lisp" |]
let gen_str_lit () = A ("\"" ^ str_pool.(Random.int (Array.length str_pool)) ^ "\"")
(* The reader's historical negative-literal bug (bare -5 lexing as a symbol)
   is fixed — reader.ml's '-' branch peeks the following digit — so negative
   int literals are generated again. Divisors for / and mod stay positive. *)
let gen_int_lit () = A (string_of_int (rint (-50) 100))
let gen_float_lit () =
  A (string_of_float (float_of_int (rint 0 40) /. 2.0))

let vars_of ty env = List.filter (fun v -> v.vty = ty) (env.vars @ env.gvars)
let has_vars ty env = vars_of ty env <> []
let pick_var ty env =
  let vs = vars_of ty env in
  (List.nth vs (Random.int (List.length vs))).vname

(* --- typed expression generators (mutually recursive) --- *)

let rec gen_int env d : sx =
  if d <= 0 then
    pick [
      4, (fun () -> gen_int_lit ());
      (if has_vars TInt env then 3 else 0), (fun () -> A (pick_var TInt env));
    ]
  else
    pick [
      3, (fun () -> gen_int_lit ());
      (if has_vars TInt env then 3 else 0), (fun () -> A (pick_var TInt env));
      4, (fun () ->
        let op = [| "+"; "-"; "*" |].(Random.int 3) in
        let n_args = if op <> "-" && flip 0.25 then 3 else 2 in
        let args = List.init n_args (fun _ -> gen_int env (d - 1)) in
        S (A op :: args));
      1, (fun () -> S [A "mod"; gen_int env (d - 1); A (string_of_int (rint 1 9))]);
      1, (fun () -> S [A "/"; gen_int env (d - 1); A (string_of_int (rint 1 9))]);
      2, (fun () -> S [A "if"; gen_bool env (d - 1); gen_int env (d - 1); gen_int env (d - 1)]);
      1, (fun () ->
        (* (let [x <int>] <int using x>) — binding evaluated in OUTER env *)
        let x = fresh "x" in
        let bind = gen_int env (d - 1) in
        let env' = { env with vars = { vname = x; vty = TInt; vne = false } :: env.vars } in
        S [A "let"; V [A x; bind]; gen_int env' (d - 1)]);
      (if env.fns <> [] then 2 else 0), (fun () ->
        let (f, arity, is_rec) = List.nth env.fns (Random.int (List.length env.fns)) in
        let arg () =
          let e = gen_int env (d - 1) in
          if is_rec then S [A "mod"; e; A "64"] else e in
        S (A f :: List.init arity (fun _ -> arg ())));
      1, (fun () -> S [A "string-length"; gen_string env (d - 1)]);
      1, (fun () -> S [A "string->number"; S [A "number->string"; gen_int env (d - 1)]]);
      1, (fun () ->
        (* string-index is int-or-nil; guard the nil case (pure, so the
           double evaluation is safe) *)
        let idx () = S [A "string-index"; gen_string env (d - 1); gen_str_lit ()] in
        let i1 = idx () in
        S [A "if"; S [A "nil?"; i1]; A "0"; i1]);
      (if env.stdlib then 1 else 0), (fun () -> S [A "length"; gen_list env (d - 1)]);
      (if env.stdlib then 1 else 0), (fun () -> S [A "foldl"; A "+"; A "0"; gen_list env (d - 1)]);
      1, (fun () -> S [A "car"; gen_list_ne env (d - 1)]);
      1, (fun () ->
        S [A "vector-get";
           V [gen_int env (d - 1); gen_int env (d - 1); gen_int env (d - 1)];
           A (string_of_int (rint 0 2))]);
      1, (fun () ->
        let k = fresh "k" in
        S [A "hash-map-get"; C [A (":" ^ k); gen_int env (d - 1)]; A (":" ^ k)]);
      1, (fun () ->
        (* immediate application ((fn (x) body) arg) *)
        let x = fresh "x" in
        let env' = { env with vars = { vname = x; vty = TInt; vne = false } :: env.vars } in
        S [S [A "fn"; S [A x]; gen_int env' (d - 1)]; gen_int env (d - 1)]);
      1, (fun () -> S [A "do"; gen_int env (d - 1); gen_int env (d - 1)]);
      2, (fun () -> gen_match TInt env d);
      (if env.stdlib then 1 else 0), (fun () ->
        (* (apply + <nonempty int list>) — apply concatenates the one
           segment and calls +, returning an int. Round-trips through braces
           as apply(+, …). *)
        S [A "apply"; A "+"; gen_list_ne env (d - 1)]);
    ]

(* A total, well-typed `(match <scrut> arm…)` producing type [ty].
   Every arm body is generated at [ty]; the scrutinee is an int so patterns are
   int literals / variables / `_` (never a list pattern against a scalar), and a
   final `_` arm guarantees no match-failure. Exercises guards (`pat if cond`)
   and — because the whole program is emitted as sexpr and also round-tripped
   through braces — the sexpr match reader and both printers. *)
and gen_match ty env d : sx =
  let gen e dd = match ty with
    | TInt -> gen_int e dd | TStr -> gen_string e dd | TBool -> gen_bool e dd
    | TFloat -> gen_float e dd | TList -> gen_list e dd in
  let scrut = gen_int env (d - 1) in
  let n = fresh "n" in
  let envn = { env with vars = { vname = n; vty = TInt; vne = false } :: env.vars } in
  S [A "match"; scrut;
     S [A (string_of_int (rint 0 4)); gen env (d - 1)];               (* literal arm *)
     S [A n; A "if"; S [A ">"; A n; A (string_of_int (rint 0 6))];    (* guarded var arm *)
        gen envn (d - 1)];
     S [A "_"; gen env (d - 1)]]                                      (* wildcard fallback *)

and gen_bool env d : sx =
  if d <= 0 then
    pick [
      2, (fun () -> A (if flip 0.5 then "true" else "false"));
      (if has_vars TBool env then 2 else 0), (fun () -> A (pick_var TBool env));
    ]
  else
    pick [
      2, (fun () -> A (if flip 0.5 then "true" else "false"));
      (if has_vars TBool env then 2 else 0), (fun () -> A (pick_var TBool env));
      4, (fun () ->
        let op = [| "<"; ">"; "<="; ">="; "=" |].(Random.int 5) in
        S [A op; gen_int env (d - 1); gen_int env (d - 1)]);
      1, (fun () -> S [A "="; gen_string env (d - 1); gen_string env (d - 1)]);
      1, (fun () -> S [A "not"; gen_bool env (d - 1)]);
      2, (fun () ->
        let op = if flip 0.5 then "and" else "or" in
        S [A op; gen_bool env (d - 1); gen_bool env (d - 1)]);
      1, (fun () -> S [A "nil?"; gen_list env (d - 1)]);
      1, (fun () -> S [A "if"; gen_bool env (d - 1); gen_bool env (d - 1); gen_bool env (d - 1)]);
    ]

and gen_string env d : sx =
  if d <= 0 then
    pick [
      3, (fun () -> gen_str_lit ());
      (if has_vars TStr env then 2 else 0), (fun () -> A (pick_var TStr env));
    ]
  else
    pick [
      3, (fun () -> gen_str_lit ());
      (if has_vars TStr env then 2 else 0), (fun () -> A (pick_var TStr env));
      3, (fun () -> S [A "string-append"; gen_string env (d - 1); gen_string env (d - 1)]);
      1, (fun () -> S [A "string-trim"; gen_string env (d - 1)]);
      1, (fun () -> S [A "number->string"; gen_int env (d - 1)]);
      1, (fun () ->
        (* appending "abcd" guarantees length >= 4, so bounds are safe *)
        S [A "string-sub";
           S [A "string-append"; gen_string env (d - 1); A "\"abcd\""];
           A "0"; A (string_of_int (rint 0 4))]);
      1, (fun () -> S [A "if"; gen_bool env (d - 1); gen_string env (d - 1); gen_string env (d - 1)]);
      1, (fun () -> S [A "->string"; gen_int env (d - 1)]);   (* f-string interpolation's lowering target *)
      2, (fun () -> gen_match TStr env d);
    ]

and gen_float env d : sx =
  if d <= 0 then
    pick [
      3, (fun () -> gen_float_lit ());
      (if has_vars TFloat env then 2 else 0), (fun () -> A (pick_var TFloat env));
    ]
  else
    pick [
      3, (fun () -> gen_float_lit ());
      (if has_vars TFloat env then 2 else 0), (fun () -> A (pick_var TFloat env));
      3, (fun () ->
        let op = [| "+"; "-"; "*" |].(Random.int 3) in
        S [A op; gen_float env (d - 1); gen_float env (d - 1)]);
      1, (fun () -> S [A "if"; gen_bool env (d - 1); gen_float env (d - 1); gen_float env (d - 1)]);
    ]

(* list of ints, statically NONEMPTY *)
and gen_list_ne env d : sx =
  if d <= 0 then
    let ne_vars = List.filter (fun v -> v.vty = TList && v.vne) (env.vars @ env.gvars) in
    if ne_vars <> [] && flip 0.4 then
      A (List.nth ne_vars (Random.int (List.length ne_vars))).vname
    else
      S (A "list" :: List.init (rint 1 3) (fun _ -> gen_int_lit ()))
  else
    pick [
      3, (fun () -> S (A "list" :: List.init (rint 1 3) (fun _ -> gen_int env (d - 1))));
      3, (fun () -> S [A "cons"; gen_int env (d - 1); gen_list env (d - 1)]);
      (if env.stdlib then 2 else 0), (fun () ->
        let a = rint 0 5 in let b = a + rint 1 6 in
        S [A "range"; A (string_of_int a); A (string_of_int b)]);
      (if env.stdlib then 1 else 0), (fun () ->
        let x = fresh "x" in
        let env' = { env with vars = { vname = x; vty = TInt; vne = false } :: env.vars } in
        S [A "map"; S [A "fn"; S [A x]; gen_int env' (d - 1)]; gen_list_ne env (d - 1)]);
      (let ne_vars = List.filter (fun v -> v.vty = TList && v.vne) (env.vars @ env.gvars) in
       (if ne_vars <> [] then 2 else 0)),
      (fun () ->
        let ne_vars = List.filter (fun v -> v.vty = TList && v.vne) (env.vars @ env.gvars) in
        A (List.nth ne_vars (Random.int (List.length ne_vars))).vname);
    ]

(* list of ints, possibly empty *)
and gen_list env d : sx =
  if d <= 0 then
    pick [
      2, (fun () -> A "nil");
      2, (fun () -> gen_list_ne env 0);
      (if has_vars TList env then 2 else 0), (fun () -> A (pick_var TList env));
    ]
  else
    pick [
      1, (fun () -> A "nil");
      4, (fun () -> gen_list_ne env d);
      (if has_vars TList env then 2 else 0), (fun () -> A (pick_var TList env));
      1, (fun () -> S [A "cdr"; gen_list_ne env (d - 1)]);
      (if env.stdlib then 1 else 0), (fun () ->
        S [A "take"; A (string_of_int (rint 0 4)); gen_list env (d - 1)]);
      (if env.stdlib then 1 else 0), (fun () ->
        let x = fresh "x" in
        let env' = { env with vars = { vname = x; vty = TInt; vne = false } :: env.vars } in
        S [A "filter"; S [A "fn"; S [A x]; gen_bool env' (d - 1)]; gen_list env (d - 1)]);
      1, (fun () -> S [A "apply"; A "list"; gen_list env (d - 1)]);  (* call-spread's lowering target *)
    ]

let gen_of_ty env d = function
  | TInt -> gen_int env d
  | TFloat -> gen_float env d
  | TBool -> gen_bool env d
  | TStr -> gen_string env d
  | TList -> gen_list env d

let random_ty env =
  pick [
    5, (fun () -> TInt);
    2, (fun () -> TBool);
    2, (fun () -> TStr);
    1, (fun () -> TFloat);
    (if env.stdlib then 2 else 1), (fun () -> TList);
  ]

let gen_printable env d : sx =
  let ty = random_ty env in
  gen_of_ty env d ty

(* --- statements (top-level forms) --- *)

(* generate a let-binding vector plus the extended env; bindings never
   reference each other (parallel-let-safe for the tree-walker) *)
let gen_bindings env d =
  let n = rint 1 2 in
  let rec go i acc_binds acc_vars =
    if i = 0 then (List.rev acc_binds, acc_vars)
    else begin
      let ty = random_ty env in
      let x = fresh "x" in
      let e = gen_of_ty env (d - 1) ty in
      let ne = (ty = TList) && (match e with
        | S (A "list" :: _ :: _) | S (A "cons" :: _) | S (A "range" :: _) -> true
        | _ -> false) in
      go (i - 1) (V [A x; e] :: acc_binds)
        ({ vname = x; vty = ty; vne = ne } :: acc_vars)
    end
  in
  let binds, new_vars = go n [] [] in
  let vec = V (List.concat_map (function V xs -> xs | x -> [x]) binds) in
  (vec, { env with vars = new_vars @ env.vars })

let stmt_print env d = [S [A "print"; gen_printable env d]]

let stmt_let_print env d =
  let vec, env' = gen_bindings env d in
  [S [A "let"; vec; S [A "print"; gen_printable env' (d - 1)]]]

let stmt_letstar_print env d =
  (* let* IS sequential; chain bindings *)
  let a = fresh "x" and b = fresh "x" in
  let env1 = { env with vars = { vname = a; vty = TInt; vne = false } :: env.vars } in
  let env2 = { env1 with vars = { vname = b; vty = TInt; vne = false } :: env1.vars } in
  [S [A "let*";
      V [A a; gen_int env (d - 1); A b; S [A "+"; A a; gen_int env1 (d - 1)]];
      S [A "print"; gen_int env2 (d - 1)]]]

let stmt_do_print env d =
  let n = rint 2 3 in
  let inner = List.init n (fun _ -> S [A "print"; gen_printable env (d - 1)]) in
  [S (A "do" :: inner)]

let stmt_do_scoped_def env d =
  (* A bare top-level `(do (def x ...) ...)` binds x
     BLOCK-LOCAL — referencing it after the `do`
     closes is an unbound-symbol error (a regression here would be
     a def leaking past the block, so the second statement below
     would print a stale value instead of erroring — a MISMATCH
     this generator would catch). Not added to
     `env.gvars`/`env.vars`: later statements must not see it either. *)
  let x = fresh "g" in
  let ty = random_ty env in
  let e = gen_of_ty env d ty in
  [S [A "do"; S [A "def"; A x; e]; S [A "print"; A x]];
   S [A "print"; A x]]

let stmt_def_value env d =
  (* (def x <expr>) — a VALUE binding: the RHS is
     evaluated at definition time and any later statement may reference x. *)
  let x = fresh "g" in
  let ty = random_ty env in
  let e = gen_of_ty env d ty in
  let ne = (ty = TList) && (match e with
    | S (A "list" :: _ :: _) | S (A "cons" :: _) | S (A "range" :: _) -> true
    | _ -> false) in
  env.gvars <- { vname = x; vty = ty; vne = ne } :: env.gvars;
  [S [A "def"; A x; e]; S [A "print"; A x]]

let stmt_def env d =
  let f = fresh "f" in
  let arity = rint 1 3 in
  let params = List.init arity (fun _ -> fresh "p") in
  let env' = { env with vars =
    List.map (fun p -> { vname = p; vty = TInt; vne = false }) params @ env.vars } in
  let body = gen_int env' d in
  env.fns <- (f, arity, false) :: env.fns;
  [S [A "def"; S (A f :: List.map (fun p -> A p) params); body]]

let stmt_def_rec env d =
  let f = fresh "f" in
  let n = fresh "p" in
  let env' = { env with vars = { vname = n; vty = TInt; vne = false } :: env.vars } in
  let op = if flip 0.8 then "+" else "*" in
  let step = gen_int env' (min 2 (d - 1)) in
  let base = gen_int_lit () in
  let def =
    S [A "def"; S [A f; A n];
       S [A "if"; S [A "<="; A n; A "0"];
          base;
          S [A op; step; S [A f; S [A "-"; A n; A "1"]]]]] in
  let call = S [A "print"; S [A f; A (string_of_int (rint 0 12))]] in
  env.fns <- (f, 1, true) :: env.fns;
  [def; call]

let stmt_with_config env d =
  let k = fresh "k" in
  let v = gen_int_lit () in
  let body =
    S [A "print";
       S [A "+"; S [A "config"; A (":" ^ k); gen_int_lit ()]; gen_int env (d - 1)]] in
  [S [A "with-config"; C [A (":" ^ k); v]; body]]

(* ------- full-grammar statements (audit-divergence probes) ------- *)

let ty_name = function TInt -> "int" | TStr -> "string" | TBool -> "bool" | _ -> "int"

let stmt_typed_let env d =
  (* (let [x : ty e] (print x)) — VM enforces, tree-walker discards *)
  let declared = [| TInt; TStr; TBool |].(Random.int 3) in
  let actual = if flip 0.6 then declared
               else [| TInt; TStr; TBool |].(Random.int 3) in
  let x = fresh "x" in
  [S [A "let"; V [A x; A ":"; A (ty_name declared); gen_of_ty env (d - 1) actual];
      S [A "print"; A x]]]

let stmt_typed_def env d =
  (* (def (f p) : ty body) then call *)
  let f = fresh "f" in
  let p = fresh "p" in
  let declared = [| TInt; TStr; TBool |].(Random.int 3) in
  let actual = if flip 0.6 then declared
               else [| TInt; TStr; TBool |].(Random.int 3) in
  let env' = { env with vars = { vname = p; vty = TInt; vne = false } :: env.vars } in
  [S [A "def"; S [A f; A p]; A ":"; A (ty_name declared); gen_of_ty env' (d - 1) actual];
   S [A "print"; S [A f; gen_int_lit ()]]]

let stmt_param_typed_def env d =
  (* (def (f p : ty) body) then call — per-parameter annotations are CHECKED
     (reader desugar); a 0.4-probability ill-typed call is a matched
     both-error probe, a well-typed call must return the body's value. *)
  let f = fresh "f" in
  let p = fresh "p" in
  let declared = [| TInt; TStr; TBool |].(Random.int 3) in
  let actual = if flip 0.6 then declared
               else [| TInt; TStr; TBool |].(Random.int 3) in
  let env' = { env with vars = { vname = p; vty = declared; vne = false } :: env.vars } in
  [S [A "def"; S [A f; A p; A ":"; A (ty_name declared)];
      gen_of_ty env' (d - 1) declared];
   S [A "print"; S [A f; gen_of_ty env (d - 1) actual]]]

let stmt_module env d =
  (* (import (module ...)) — VM compiles only EDef children *)
  let m = fresh "m" in
  let p = fresh "p" in
  let penv = { vars = [{ vname = p; vty = TInt; vne = false }];
               fns = []; stdlib = false; gvars = [] } in
  let def = S [A "def"; S [A m; A p]; gen_int penv (d - 1)] in
  let children =
    if flip 0.5 then [S [A "print"; gen_str_lit ()]; def]  (* non-def child *)
    else [def] in
  env.fns <- (m, 1, false) :: env.fns;
  [S [A "import"; S (A "module" :: children)];
   S [A "print"; S [A m; gen_int_lit ()]]]

let stmt_module_sibling env d =
  (* Module-body children see EARLIER siblings, letrec*-style
     — a sibling function def, a sibling value def, and a bare in-module
     statement all resolve through the module's own local slots (a
     regression here would resolve any of these globally at construction
     time and raise "unbound symbol" in the VM, since the tree-walker
     already threads `env_acc` forward across module children — e.g.
     exactly `(import (module (def (f x) ...) (print (f 1))))`). *)
  let f = fresh "m" and a = fresh "m" and b = fresh "m" in
  let p = fresh "p" in
  let penv = { vars = [{ vname = p; vty = TInt; vne = false }];
               fns = []; stdlib = false; gvars = [] } in
  let def_f = S [A "def"; S [A f; A p]; gen_int penv (d - 1)] in
  let def_a = S [A "def"; A a; gen_int_lit ()] in
  (* def_b: a value def referencing BOTH a sibling value (a) and a sibling
     function (f) *)
  let def_b = S [A "def"; A b; S [A "+"; A a; S [A f; A "1"]]] in
  (* bare module statement referencing siblings b and f *)
  let stmt = S [A "print"; S [A "+"; A b; S [A f; A "2"]]] in
  env.fns <- (f, 1, false) :: env.fns;
  env.gvars <- { vname = b; vty = TInt; vne = false } :: env.gvars;
  [S [A "import"; S [A "module"; def_f; def_a; def_b; stmt]];
   S [A "print"; S [A f; gen_int_lit ()]];
   S [A "print"; A b]]

let stmt_load_module env _d =
  (* (load-module "<abs stdlib>") then use a stdlib fn — an opcode probe *)
  env.stdlib <- true;
  [S [A "load-module"; A ("\"" ^ !stdlib_path ^ "\"")];
   S [A "print"; S [A "length"; S [A "range"; A "0"; A (string_of_int (rint 1 6))]]]]

(* Islands: a FIXED fixture island, pinned once at startup by running
   `pp --update` on a seed file (which also exercises the pin rewriter and
   fills the cache). Only pinned file: islands over this fixture are ever
   generated — network islands stay out (real nondeterminism). Setup failure
   degrades to disabled, never to a flaky grammar. *)
let island_fixture : (string * string) option Lazy.t = lazy (
  try
    let dir = Filename.temp_file "ppfuzz-island" "" in
    Sys.remove dir;
    Unix.mkdir dir 0o755;
    (* `.pp` dispatches to the brace reader, so the fixture's
       entry file (found by island.ml's entry_file via the literal name
       "entry.pp") must hold brace-surface text. The seed file below stays
       sexpr — it's read by `pp --update` as an argument file, so it gets
       the `.ppl` extension (sexpr, forever supported) instead. *)
    let oc = open_out (Filename.concat dir "entry.pp") in
    output_string oc "let isl-x = 42\ndef isl-add(n) { n + 5 }\n";
    close_out oc;
    let seed_f = Filename.temp_file "ppfuzz-island-seed" ".ppl" in
    let oc = open_out seed_f in
    output_string oc ("(import (island file:" ^ dir ^ "))\n(print isl-x)\n");
    close_out oc;
    let rc = Sys.command (Filename.quote !pp_bin ^ " --update "
                          ^ Filename.quote seed_f ^ " >/dev/null 2>&1") in
    if rc <> 0 then None
    else begin
      let ch = open_in seed_f in
      let line1 = input_line ch in
      close_in ch;
      let is_hex c = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') in
      let n = String.length line1 in
      let rec scan i =
        if i >= n then None
        else begin
          let j = ref i in
          while !j < n && is_hex line1.[!j] do incr j done;
          if !j - i = 64 then Some (String.sub line1 i 64)
          else scan (if !j > i then !j else i + 1)
        end
      in
      match scan 0 with
      | Some pin -> Some (dir, pin)
      | None -> None
    end
  with _ -> None)

let stmt_island env d =
  match Lazy.force island_fixture with
  | None -> stmt_print env d  (* setup failed: degrade, don't flake *)
  | Some (dir, pin) ->
      env.fns <- ("isl-add", 1, false) :: env.fns;
      [S [A "import"; S [A "island"; A ("file:" ^ dir); A ("\"" ^ pin ^ "\"")]];
       S [A "print"; S [A "isl-add"; A (string_of_int (rint 0 9))]]]

let stmt_config_computed env d =
  (* computed config key — VM requires compile-time literal *)
  let k = fresh "k" in
  let klen = String.length k in
  let k1 = String.sub k 0 (klen / 2) and k2 = String.sub k (klen / 2) (klen - klen / 2) in
  [S [A "with-config"; C [A (":" ^ k); gen_int_lit ()];
      S [A "print";
         S [A "config";
            S [A "string-append"; A ("\"" ^ k1 ^ "\""); A ("\"" ^ k2 ^ "\"")];
            gen_int env (d - 1)]]]]

let stmt_perform env d =
  (* perform log with no handler: builtin logs to stderr, returns nil *)
  if flip 0.5 then [S [A "perform"; A "log"; gen_string env (d - 1)]]
  else [S [A "print"; S [A "perform"; A "log"; gen_string env (d - 1)]]]

let stmt_with_handler env d =
  (* handler over log returning an int *)
  let m = fresh "p" in
  let henv = { env with vars = { vname = m; vty = TStr; vne = false } :: env.vars } in
  let hbody =
    if flip 0.5 then gen_int henv (d - 1)
    else S [A "do"; S [A "print"; S [A "string-append"; A "\"h:\""; A m]];
            gen_int henv (d - 1)] in
  [S [A "with-handler"; V [A "log"; S [A "fn"; S [A m]; hbody]];
      S [A "print"; S [A "perform"; A "log"; gen_string env (d - 1)]]]]

let stmt_handler_leak env d =
  (* with-handler whose body ends in a tail call — if the VM never pops the
     handler, a later perform diverges *)
  let f = fresh "f" in
  let p = fresh "p" in
  let env' = { env with vars = { vname = p; vty = TInt; vne = false } :: env.vars } in
  let m = fresh "p" in
  [S [A "def"; S [A f; A p]; gen_int env' (d - 1)];
   S [A "with-handler"; V [A "log"; S [A "fn"; S [A m]; A "77"]];
      S [A f; gen_int_lit ()]];
   S [A "print"; S [A "perform"; A "log"; gen_str_lit ()]]]

let stmt_deep_rec _env _d =
  (* deep recursion — stack-safety; tail and non-tail variants *)
  let f = fresh "f" in
  let n = fresh "p" in
  if flip 0.5 then begin
    let depth = [| 500; 2000; 5000 |].(Random.int 3) in
    [S [A "def"; S [A f; A n];
        S [A "if"; S [A "<="; A n; A "0"]; A "0";
           S [A "+"; A "1"; S [A f; S [A "-"; A n; A "1"]]]]];
     S [A "print"; S [A f; A (string_of_int depth)]]]
  end else begin
    let acc = fresh "p" in
    let depth = [| 5000; 20000 |].(Random.int 2) in
    [S [A "def"; S [A f; A n; A acc];
        S [A "if"; S [A "<="; A n; A "0"]; A acc;
           S [A f; S [A "-"; A n; A "1"]; S [A "+"; A acc; A "1"]]]];
     S [A "print"; S [A f; A (string_of_int depth); A "0"]]]
  end

let stmt_big_map env _d =
  (* must not reference stdlib fns unless the load form is actually present *)
  let prelude =
    if env.stdlib then []
    else begin
      env.stdlib <- true;
      [S [A "load"; A ("\"" ^ !stdlib_path ^ "\"")]]
    end in
  let x = fresh "x" in
  let n = rint 50 200 in
  prelude @
  [S [A "print";
      S [A "length";
         S [A "map"; S [A "fn"; S [A x]; S [A "+"; A x; A "1"]];
            S [A "range"; A "0"; A (string_of_int n)]]]]]

let stmt_eq_list env d =
  (* (= E E) with textually identical E — tree-walker dedups thunks *)
  let e = gen_list_ne env (d - 1) in
  [S [A "print"; S [A "="; e; e]]]

let stmt_seq_let env d =
  (* let binding referencing a sibling *)
  let a = fresh "x" and b = fresh "x" in
  [S [A "let"; V [A a; gen_int env (d - 1); A b; S [A "+"; A a; A "1"]];
      S [A "print"; A b]]]

let stmt_quote_special _env _d =
  if flip 0.5 then [S [A "print"; S [A "quote"; S [A "if"; A "1"; A "2"; A "3"]]]]
  else [S [A "print"; S [A "quote"; S [A "let"; V [A "x"; A "1"]; A "x"]]]]

(* The tree-walker matches structurally via Types.match_pattern and is
   immune to shadowing of car/cdr/nil?/not/error. This shadows every
   one of them in a `let` and runs a fixed match; the tree-walker must
   still print 6, so any regression surfaces as an ordinary fuzz
   MISMATCH. The whole fragment is emitted verbatim (a single atom)
   because its point is to be exactly this shape, not to vary.
   The shadows live inside an immediately-applied fn so they stay
   function-local. Supersedes the former tests/063 fixed oracle.
   `=` is deliberately NOT shadowed: the brace surface cannot express an
   operator-named binding, so the program would fail the roundtrip gate
   for surface reasons, not semantic ones. *)
let stmt_match_shadow _env _d =
  [A "((fn () (let (car 0 cdr 0 nil? 0 not 0 error 0) \
        (match (list 1 2 3) ((list a b c) (+ a (+ b c))) (_ 0)))))" ]
let stmt_defmacro _env _d =
  (* (defmacro (name x) (list (quote +) x x)) then (print (name N)) —
     the macro receives its argument FORM as a quoted value at expansion
     time (never evaluating it inside the macro body) and builds a new form
     with list/quote, converted back to syntax (Types.value_to_expr) before
     the evaluator ever sees it — a correct shared expansion point prints
     2*N identically. The argument is always a bare literal (never a
     side-effecting expr), so the doubled reference in the expansion can
     never double an observable effect — this arm is purely about expansion
     parity, not evaluation-order semantics. Fresh macro name per call site
     (fuzz.ml's `fresh`) since gen_program may pick this arm more than once
     in one program. *)
  let name = fresh "mac" in
  let n = rint 1 20 in
  [S [A "defmacro"; S [A name; A "x"];
      S [A "list"; S [A "quote"; A "+"]; A "x"; A "x"]];
   S [A "print"; S [A name; A (string_of_int n)]]]

(* --- program generator --- *)

let load_stdlib_form () =
  S [A "load"; A ("\"" ^ !stdlib_path ^ "\"")]

let gen_program (gram : string) (iter : int) : string =
  Random.full_init [| !seed; iter |];
  name_counter := 0;
  let env = { vars = []; fns = []; stdlib = false; gvars = [] } in
  let forms = ref [] in
  let emit fs = forms := !forms @ fs in
  if flip 0.7 then begin env.stdlib <- true; emit [load_stdlib_form ()] end;
  let d = !max_depth in
  let core_stmts = [
    6, (fun () -> stmt_print env d);
    3, (fun () -> stmt_let_print env d);
    2, (fun () -> stmt_letstar_print env d);
    2, (fun () -> stmt_do_print env d);
    3, (fun () -> stmt_def env d);
    2, (fun () -> stmt_def_rec env d);
    3, (fun () -> stmt_def_value env d);
    2, (fun () -> stmt_with_config env d);
  ] in
  let full_stmts = core_stmts @ [
    2, (fun () -> stmt_typed_let env d);
    2, (fun () -> stmt_typed_def env d);
    2, (fun () -> stmt_param_typed_def env d);
    2, (fun () -> stmt_module env d);
    2, (fun () -> stmt_module_sibling env d);
    1, (fun () -> stmt_do_scoped_def env d);
    1, (fun () -> stmt_load_module env d);
    1, (fun () -> stmt_island env d);
    1, (fun () -> stmt_config_computed env d);
    2, (fun () -> stmt_perform env d);
    2, (fun () -> stmt_with_handler env d);
    1, (fun () -> stmt_handler_leak env d);
    1, (fun () -> stmt_deep_rec env d);
    1, (fun () -> stmt_big_map env d);
    1, (fun () -> stmt_eq_list env d);
    1, (fun () -> stmt_seq_let env d);
    1, (fun () -> stmt_quote_special env d);
    2, (fun () -> stmt_defmacro env d);
    1, (fun () -> stmt_match_shadow env d);
  ] in
  let table = if gram = "full" then full_stmts else core_stmts in
  let n_stmts = rint 2 5 in
  for _ = 1 to n_stmts do emit (pick table) done;
  (* guarantee at least one observable print *)
  if not (List.exists (function
      | S (A "print" :: _) -> true
      | S (A ("let" | "let*" | "with-config" | "with-handler") :: _) -> true
      | S (A "do" :: _) -> true
      | _ -> false) !forms)
  then emit (stmt_print env d);
  render_program !forms

(* ---------------------------------------------------- Subprocess runner -- *)

type outcome = {
  status : [ `Exit of int | `Signal of int | `Timeout ];
  out : string;
  err : string;
}

let read_file path =
  try
    let ch = open_in_bin path in
    let n = in_channel_length ch in
    let s = really_input_string ch n in
    close_in ch; s
  with _ -> ""

let devnull = lazy (Unix.openfile "/dev/null" [Unix.O_RDONLY] 0)

let tmp_out = lazy (Filename.temp_file "ppfuzz" ".out")
let tmp_err = lazy (Filename.temp_file "ppfuzz" ".err")

let run_backend (args : string list) (file : string) : outcome =
  let out_f = Lazy.force tmp_out and err_f = Lazy.force tmp_err in
  let fd_out = Unix.openfile out_f [Unix.O_WRONLY; Unix.O_CREAT; Unix.O_TRUNC] 0o600 in
  let fd_err = Unix.openfile err_f [Unix.O_WRONLY; Unix.O_CREAT; Unix.O_TRUNC] 0o600 in
  let argv = Array.of_list (!pp_bin :: args @ [file]) in
  let pid =
    try Unix.create_process !pp_bin argv (Lazy.force devnull) fd_out fd_err
    with Unix.Unix_error (e, _, _) ->
      Unix.close fd_out; Unix.close fd_err;
      prerr_endline ("fatal: cannot execute " ^ !pp_bin ^ ": " ^ Unix.error_message e);
      exit 2
  in
  Unix.close fd_out; Unix.close fd_err;
  let deadline = Unix.gettimeofday () +. float_of_int !timeout_ms /. 1000.0 in
  let rec wait () =
    let (p, st) = Unix.waitpid [Unix.WNOHANG] pid in
    if p = 0 then begin
      if Unix.gettimeofday () > deadline then begin
        (try Unix.kill pid Sys.sigkill with _ -> ());
        ignore (Unix.waitpid [] pid);
        `Timeout
      end else begin
        Unix.sleepf 0.002;
        wait ()
      end
    end else
      match st with
      | Unix.WEXITED n -> `Exit n
      | Unix.WSIGNALED s | Unix.WSTOPPED s -> `Signal s
  in
  let status = wait () in
  { status; out = read_file out_f; err = read_file err_f }

(* ------------------------------------------------------------ Verdicts -- *)

type verdict =
  | Pass
  | Mismatch of string   (* signature *)
  | BothError of string  (* signature *)
  | Crash of string      (* signature *)

(* normalize for signature grouping: quoted strings -> "S", digit runs -> #,
   newlines -> spaces, cap length.  Aggressive on purpose: signatures should
   count BUG CLASSES, not distinct payloads. *)
let norm ?(max_len = 48) s =
  let b = Buffer.create (String.length s) in
  let n = String.length s in
  let i = ref 0 in
  let last_hash = ref false in
  while !i < n do
    let c = s.[!i] in
    if c = '"' || (c = '\\' && !i + 1 < n && s.[!i + 1] = '"') then begin
      (* skip a quoted span, possibly backslash-escaped; emit a placeholder *)
      let esc = c = '\\' in
      i := !i + (if esc then 2 else 1);
      let closed = ref false in
      while not !closed && !i < n do
        if esc && s.[!i] = '\\' && !i + 1 < n && s.[!i + 1] = '"' then begin
          i := !i + 2; closed := true
        end else if (not esc) && s.[!i] = '"' then begin
          incr i; closed := true
        end else incr i
      done;
      Buffer.add_string b "\"S\"";
      last_hash := false
    end else begin
      if c >= '0' && c <= '9' then begin
        if not !last_hash then Buffer.add_char b '#';
        last_hash := true
      end else begin
        last_hash := false;
        if c = '\n' then Buffer.add_char b ' ' else Buffer.add_char b c
      end;
      incr i
    end
  done;
  let s = Buffer.contents b in
  if String.length s > max_len then String.sub s 0 max_len else s

(* extract a stable error tag from stderr *)
let error_tag (err : string) : string =
  let lines = String.split_on_char '\n' err in
  let fatal =
    List.fold_left (fun acc l ->
      let prefix = "Fatal error: exception " in
      let clean = "pp: error: " in
      if String.length l > String.length prefix
         && String.sub l 0 (String.length prefix) = prefix
      then Some (String.sub l (String.length prefix)
                   (String.length l - String.length prefix))
      else if String.length l > String.length clean
              && String.sub l 0 (String.length clean) = clean
      then
        (* pp's clean error line carries the raw message; re-wrap it in the
           Failure("…") shape so the normalization below applies unchanged. *)
        Some (Printf.sprintf "Failure(\"%s\")"
                (String.sub l (String.length clean)
                   (String.length l - String.length clean)))
      else acc) None lines
  in
  match fatal with
  | None -> "no-fatal-line"
  | Some rest ->
      (* Failure("msg") — pull out msg, strip nested builtin wrappers *)
      let msg =
        if String.length rest > 9 && String.sub rest 0 9 = "Failure(\"" then begin
          let inner = String.sub rest 9 (String.length rest - 9) in
          let inner =
            match String.rindex_opt inner '"' with
            | Some i -> String.sub inner 0 i
            | None -> inner in
          (* repeatedly strip "builtin 'X' failed: " *)
          let rec strip s =
            let pfx = "builtin '" in
            if String.length s > String.length pfx
               && String.sub s 0 (String.length pfx) = pfx then
              match String.index_opt s ':' with
              | Some i when i + 2 <= String.length s ->
                  strip (String.sub s (i + 2) (String.length s - i - 2))
              | _ -> s
            else s
          in
          let m = strip inner in
          (* drop value payloads: "type mismatch: expected int, got false"
             and friends group by the ", got"-free prefix *)
          let m =
            let pat = ", got " in
            let rec find i =
              if i + String.length pat > String.length m then None
              else if String.sub m i (String.length pat) = pat then Some i
              else find (i + 1) in
            match find 0 with
            | Some i -> String.sub m 0 i ^ ", got _"
            | None -> m in
          "Failure:" ^ m
        end else
          (* non-Failure exception: keep constructor name only *)
          (match String.index_opt rest '(' with
           | Some i -> String.sub rest 0 i
           | None -> rest)
      in
      norm msg

let sig_of_verdict = function
  | Pass -> None
  | Mismatch s | BothError s | Crash s -> Some s



(* -------------------------------------------------------------- Shrink -- *)

(* Since gen_program renders directly, the shrinker works on a re-parsed sx
   tree of the rendered program.  Tiny parser for our OWN rendered output;
   atoms are whitespace-delimited and generated string literals never contain
   quotes, backslashes, or brackets. *)

let parse_program (src : string) : sx list =
  let n = String.length src in
  let pos = ref 0 in
  let peek () = if !pos < n then Some src.[!pos] else None in
  let rec skip_ws () =
    match peek () with
    | Some (' ' | '\n' | '\t') -> incr pos; skip_ws ()
    | _ -> ()
  in
  let rec parse_one () : sx =
    skip_ws ();
    match peek () with
    | Some '(' -> incr pos; S (parse_seq ')')
    | Some '[' -> incr pos; V (parse_seq ']')
    | Some '{' -> incr pos; C (parse_seq '}')
    | Some '"' ->
        let start = !pos in
        incr pos;
        while !pos < n && src.[!pos] <> '"' do incr pos done;
        incr pos;
        A (String.sub src start (!pos - start))
    | Some _ ->
        let start = !pos in
        let stop c = c = ' ' || c = '\n' || c = '\t' || c = '(' || c = ')'
                     || c = '[' || c = ']' || c = '{' || c = '}' in
        while !pos < n && not (stop src.[!pos]) do incr pos done;
        A (String.sub src start (!pos - start))
    | None -> failwith "parse_program: eof"
  and parse_seq close =
    skip_ws ();
    match peek () with
    | Some c when c = close -> incr pos; []
    | Some _ -> let x = parse_one () in x :: parse_seq close
    | None -> failwith "parse_program: unterminated"
  in
  let rec top () =
    skip_ws ();
    if !pos >= n then [] else let x = parse_one () in x :: top ()
  in
  top ()

(* enumerate node count; replace node #target (preorder, roots first) *)
let rec count_nodes sx =
  match sx with
  | A _ -> 1
  | S xs | V xs | C xs -> 1 + List.fold_left (fun a x -> a + count_nodes x) 0 xs

let replace_node (sx : sx) (target : int) (repl : sx) : sx =
  let idx = ref (-1) in
  let rec go sx =
    incr idx;
    if !idx = target then repl
    else match sx with
      | A _ -> sx
      | S xs -> S (List.map go xs)
      | V xs -> V (List.map go xs)
      | C xs -> C (List.map go xs)
  in
  go sx

let node_at (sx : sx) (target : int) : sx =
  let idx = ref (-1) in
  let found = ref None in
  let rec go sx =
    incr idx;
    if !idx = target then found := Some sx;
    (match sx with
     | A _ -> ()
     | S xs | V xs | C xs -> List.iter go xs)
  in
  go sx;
  match !found with Some x -> x | None -> A "?"

let prog_size forms = String.length (render_program forms)

(* candidate reductions for a program, in decreasing aggressiveness *)
let shrink_candidates (forms : sx list) : sx list list =
  let cands = ref [] in
  let add c = cands := c :: !cands in
  let nf = List.length forms in
  (* 1. drop a top-level form *)
  if nf > 1 then
    for i = 0 to nf - 1 do
      add (List.filteri (fun j _ -> j <> i) forms)
    done;
  (* 2. hoist a child over its parent; 3. replace subtree with a literal *)
  List.iteri (fun fi form ->
    let n = count_nodes form in
    for node_i = 1 to n - 1 do        (* skip the root of the form itself *)
      (match node_at form node_i with
       | S (_ :: args) when args <> [] ->
           List.iter (fun arg ->
             add (List.mapi (fun j f ->
               if j = fi then replace_node f node_i arg else f) forms)
           ) args
       | _ -> ());
      (match node_at form node_i with
       | A a ->
           (* shrink integer atoms *)
           (match int_of_string_opt a with
            | Some v when v <> 0 && v <> 1 ->
                let v' = if abs v > 4 then v / 2 else (if v > 0 then v - 1 else v + 1) in
                add (List.mapi (fun j f ->
                  if j = fi then replace_node f node_i (A (string_of_int v')) else f) forms)
            | _ -> ())
       | _ ->
           List.iter (fun r ->
             add (List.mapi (fun j f ->
               if j = fi then replace_node f node_i r else f) forms))
             [A "0"; A "1"; A "true"; A "nil"; A "\"a\""])
    done
  ) forms;
  List.rev !cands

(* `.pp` dispatches to the brace reader; every program this
   fuzzer generates is sexpr text (the `sx` tree's printer emits classic
   S-expressions), so the scratch file keeps the `.ppl` extension — the
   sexpr surface is still fully supported, just no longer the default for
   `.pp`. `--roundtrip-braces` (below) also relies on this: it refuses a
   file whose extension already dispatches to the brace reader. *)
let prog_file = lazy (Filename.temp_file "ppfuzz" ".ppl")

(* The reader round-trip check (sexpr -> braces -> re-read; AST +
   LAW-20 hash equality), run in-process by the interpreter itself. *)
let run_roundtrip (src : string) : outcome =
  let f = Lazy.force prog_file in
  let ch = open_out f in
  output_string ch src; close_out ch;
  run_backend ["--roundtrip-braces"] f

(* Single walker run — writes the program file and runs `pp f`. *)
let run_walker (src : string) : outcome =
  let f = Lazy.force prog_file in
  let ch = open_out f in
  output_string ch src; close_out ch;
  run_backend [] f

(* Single-engine verdict: a roundtrip failure always gates as Mismatch.
   Otherwise, check the walker outcome: crashes are hard failures,
   non-zero exits with known error tags are soft (BothError). *)
let judge_walker (w : outcome) : verdict =
  let crash_of o =
    match o.status with
    | `Timeout -> Some "crash:timeout"
    | `Signal s -> Some (Printf.sprintf "crash:signal-%d" s)
    | `Exit n when n > 128 -> Some (Printf.sprintf "crash:exit-%d" n)
    | _ -> None
  in
  match crash_of w with
  | Some s -> Crash s
  | None ->
      if w.status = `Exit 0 then Pass
      else
        let tag = error_tag w.err in
        BothError ("error:" ^ tag)

let judge_full (rt : outcome) (w : outcome) : verdict =
  if rt.status <> `Exit 0 then Mismatch ("roundtrip:" ^ error_tag rt.err)
  else judge_walker w
let special_form_heads =
  ["def"; "defmacro"; "defnode"; "let"; "let*"; "module"; "import";
   "load"; "load-module"; "quote"; "quasiquote"; "unquote"; "fn"; "match"; "effect";
   "perform"; "with-handler"; "with-config"; "island"; "node"]

let is_special_form_head s = List.mem s special_form_heads

let is_literal_atom s =
  (try ignore (int_of_string s); true with _ ->
   try ignore (float_of_string s); true with _ ->
   (String.length s >= 2 && s.[0] = '"' && s.[String.length s - 1] = '"')
   || s = "true" || s = "false" || s = "nil")

type eligible = { e_form : int; e_node : int }

(* Collect eligible wrap positions by iterating with node_at directly.
   This guarantees index consistency with replace_node/node_at. *)
(* Simplified context check: only reject positions inside quote/quasiquote
   or inside load/import/defmacro (non-expression argument positions). *)
let is_expr_position form target =
  let idx = ref (-1) in
  let ok = ref true in
  let found = ref false in
  let rec count sx =
    incr idx;
    if !idx = target then ok := false
    else if not !found then match sx with
    | A _ -> ()
    | S xs | V xs | C xs -> List.iter count xs
  in
  let rec go sx =
    incr idx;
    if !idx = target then ()
    else if not !found then match sx with
    | A _ -> ()
    | V xs -> List.iter go xs
    | C xs -> List.iter go xs
    | S (A head :: args) ->
        let skip = head = "quote" || head = "quasiquote"
                   || head = "load" || head = "load-module" || head = "import"
                   || head = "defmacro" || head = "def" || head = "fn" in
        if skip then
          List.iter count (A head :: args)
        else if head = "let" || head = "let*" then
          (* Count head and binding vector; walk body normally *)
          let () = count (A head) in
          (match args with
           | bind :: rest -> count bind; List.iter go rest
           | _ -> List.iter go args)
        else if head = "match" then
          let () = count (A head) in
          (match args with
           | scrut :: arms ->
               go scrut;
               List.iter (fun arm ->
                 match arm with
                 | S parts when List.length parts >= 2 ->
                     let n = List.length parts in
                     let () = incr idx in
                     if !idx = target then ok := false
                     else begin
                       List.iter count (List.filteri (fun i _ -> i < n - 1) parts);
                       go (List.nth parts (n - 1))
                     end
                 | _ -> go arm
               ) arms
           | _ -> ())
        else
          List.iter go (A head :: args)
    | S xs ->
        List.iter go xs
  in
  go form;
  !ok

let collect_eligible forms =
  let result = ref [] in
  List.iteri (fun fi form ->
    let n = count_nodes form in
    for node_i = 1 to n - 1 do
      let sx = node_at form node_i in
      let eligible = match sx with
        | A s -> is_literal_atom s
        | S (A head :: _) -> not (is_special_form_head head)
        | S (_ :: _) -> true
        | _ -> false
      in
      if eligible && is_expr_position form node_i then
        result := { e_form = fi; e_node = node_i } :: !result
    done
  ) forms;
  List.rev !result

let apply_do_wrap (e : sx) : sx = S [A "do"; e]

let apply_let_wrap (e : sx) : sx =
  let name = fresh "t" in
  S [A "let"; V [A name; e]; A name]

let apply_eta_wrap (e : sx) : sx =
  let name = fresh "t" in
  S [S [A "fn"; S [A name]; A name]; e]

let derive_twin (src : string) : string option =
  let forms = parse_program src in
  let eligible = collect_eligible forms in
  if eligible = [] then None
  else begin
    let k = min (List.length eligible) (rint 1 3) in
    let used = Hashtbl.create 3 in
    let picks = ref [] in
    while List.length !picks < k do
      let idx = Random.int (List.length eligible) in
      if not (Hashtbl.mem used idx) then begin
        Hashtbl.add used idx true;
        picks := (List.nth eligible idx) :: !picks
      end
    done;
    let transforms = [apply_do_wrap; apply_let_wrap; apply_eta_wrap] in
    let sorted_picks = List.sort (fun a b ->
      let c = compare a.e_form b.e_form in
      if c <> 0 then c else compare b.e_node a.e_node
    ) !picks in
    let new_forms = List.fold_left (fun acc picked ->
      let form = List.nth acc picked.e_form in
      let e = node_at form picked.e_node in
      let t = List.nth transforms (Random.int 3) in
      let wrapped = replace_node form picked.e_node (t e) in
      List.mapi (fun j f -> if j = picked.e_form then wrapped else f) acc
    ) forms sorted_picks in
    Some (render_program new_forms)
  end

let first_diff_lines a b =
  let la = String.split_on_char '\n' a and lb = String.split_on_char '\n' b in
  let rec go la lb =
    match la, lb with
    | [], [] -> ("", "")
    | x :: ra, y :: rb -> if x = y then go ra rb else (x, y)
    | x :: _, [] -> (x, "<eof>")
    | [], y :: _ -> ("<eof>", y)
  in
  go la lb

let judge_meta (a : outcome) (b : outcome) : verdict =
  let crash_of side o = match o.status with
    | `Timeout -> Some (Printf.sprintf "crash:%s:timeout" side)
    | `Signal s -> Some (Printf.sprintf "crash:%s:signal-%d" side s)
    | `Exit n when n > 128 -> Some (Printf.sprintf "crash:%s:exit-%d" side n)
    | _ -> None
  in
  match crash_of "p" a, crash_of "t" b with
  | Some s, _ | _, Some s -> Crash s
  | None, None ->
      let a_ok = a.status = `Exit 0 and b_ok = b.status = `Exit 0 in
      if a_ok && b_ok then begin
        if a.out <> b.out then
          let (a_l, b_l) = first_diff_lines a.out b.out in
          Mismatch ("metamorphic:outdiff:" ^ norm ~max_len:28 a_l ^ "|" ^ norm ~max_len:28 b_l)
        else if a.err <> b.err then
          let (a_l, b_l) = first_diff_lines a.err b.err in
          Mismatch ("metamorphic:logdiff:" ^ norm ~max_len:28 a_l ^ "|" ^ norm ~max_len:28 b_l)
        else Pass
      end
      else if a_ok && not b_ok then
        Mismatch ("metamorphic:exitdiff:t-err:" ^ error_tag b.err)
      else if b_ok && not a_ok then
        Mismatch ("metamorphic:exitdiff:p-err:" ^ error_tag a.err)
      else
        let ta = error_tag a.err and tb = error_tag b.err in
        if ta = tb then Pass
        else Mismatch ("metamorphic:both-error:" ^ ta ^ "|" ^ tb)

(* Run a single program through pp f and return the outcome *)
let run_single (src : string) : outcome =
  let f = Lazy.force prog_file in
  let ch = open_out f in output_string ch src; close_out ch;
  run_backend [] f

let run_metamorphic (src : string) (twin : string) : verdict =
  let p_out = run_single src in
  let t_out = run_single twin in
  judge_meta p_out t_out

let is_meta_signature s =
  String.length s >= 12 && String.sub s 0 12 = "metamorphic:"

let shrink (src : string) (signature : string) : string =
  let is_meta = is_meta_signature signature in
  let execs = ref 0 in
  let same_sig forms =
    if !execs >= !shrink_budget then false
    else begin
      incr execs;
      if is_meta then begin
        let text = render_program forms in
        let h = Hashtbl.hash text in
        Random.full_init [| h |];
        name_counter := 0;
        match derive_twin text with
        | Some twin ->
            let p_out = run_single text in
            let t_out = run_single twin in
            sig_of_verdict (judge_meta p_out t_out) = Some signature
        | None -> false
      end else begin
        let w = run_walker (render_program forms) in
        let rt = run_roundtrip (render_program forms) in
        sig_of_verdict (judge_full rt w) = Some signature
      end
    end
  in
  let rec fixpoint forms =
    if !execs >= !shrink_budget then forms
    else begin
      let size0 = prog_size forms in
      let better =
        List.find_opt (fun c -> prog_size c < size0 && same_sig c)
          (shrink_candidates forms)
      in
      match better with
      | Some c -> fixpoint c
      | None -> forms
    end
  in
  try render_program (fixpoint (parse_program src))
  with _ -> src   (* shrinker must never lose the repro *)

(* ---------------------------------------------------------------- Main -- *)

let sanitize_sig s =
  let b = Buffer.create (String.length s) in
  String.iter (fun c ->
    if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
       || (c >= '0' && c <= '9') || c = '-' || c = '_' || c = '.'
    then Buffer.add_char b c
    else Buffer.add_char b '_') s;
  let s = Buffer.contents b in
  let s = if String.length s > 70 then String.sub s 0 70 else s in
  s ^ "-" ^ Printf.sprintf "%08x" (Hashtbl.hash s land 0xffffffff)

let mkdir_p dir =
  let rec go d =
    if d <> "" && d <> "." && d <> "/" && not (Sys.file_exists d) then begin
      go (Filename.dirname d);
      (try Unix.mkdir d 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ())
    end
  in
  go dir

let outcome_to_string (o : outcome) : string =
  let st = match o.status with
    | `Exit n -> Printf.sprintf "exit %d" n
    | `Signal s -> Printf.sprintf "signal %d" s
    | `Timeout -> "timeout" in
  Printf.sprintf "status: %s\n--- stdout ---\n%s--- stderr ---\n%s" st o.out o.err

let write_file path content =
  let ch = open_out path in output_string ch content; close_out ch

type sig_info = {
  mutable n_hits : int;
  mutable examples : int;    (* how many example programs saved *)
  kind : [ `Mismatch | `BothError | `Crash ];
  first_iter : int;
  mutable min_repro : string;
}

let () =
  parse_cli ();
  if !dump_iter >= 0 then begin
    print_string (gen_program !grammar !dump_iter);
    exit 0
  end;
  let sigs : (string, sig_info) Hashtbl.t = Hashtbl.create 64 in
  let n_pass = ref 0 and n_mismatch = ref 0 and n_both = ref 0 and n_crash = ref 0 in
  (* Programs whose error tag is whitelisted stay a soft class. *)
  let n_errpass = ref 0 in
  (* Round-trip accounting — every program is checked; failures are
     gating mismatches with a `roundtrip:` signature. *)
  let n_rt_checked = ref 0 and n_rt_fail = ref 0 in
  let n_meta_checked = ref 0 and n_meta_fail = ref 0 in
  Printf.printf "pp-fuzz: grammar=%s seed=%d start=%d count=%d depth=%d timeout=%dms pp=%s\n%!"
    !grammar !seed !start_iter !count !max_depth !timeout_ms !pp_bin;
  for i = !start_iter to !start_iter + !count - 1 do
    let meta_twin_src = ref None in
    let src = gen_program !grammar i in
    let w = run_walker src in
    let rt = run_roundtrip src in
    incr n_rt_checked;
    if rt.status <> `Exit 0 then incr n_rt_fail;
    let v0 = judge_full rt w in
    let v = match v0 with
      | Pass when not !no_metamorphic ->
          incr n_meta_checked;
          Random.full_init [| !seed; i; 0x4D354124 |];
          (match derive_twin src with
           | Some twin ->
               meta_twin_src := Some twin;
               let mv = run_metamorphic src twin in
               if mv <> Pass then incr n_meta_fail;
               mv
           | None -> Pass)
      | _ -> v0
    in
    (match v with
     | Pass ->
         incr n_pass;
         if w.status <> `Exit 0 then incr n_errpass
     | Mismatch _ -> incr n_mismatch
     | BothError _ -> incr n_both
     | Crash _ -> incr n_crash);
    (match sig_of_verdict v with
     | None -> ()
     | Some s ->
         let kind = (match v with
           | Mismatch _ -> `Mismatch | BothError _ -> `BothError
           | Crash _ -> `Crash | Pass -> assert false) in
         let info =
           match Hashtbl.find_opt sigs s with
           | Some info -> info.n_hits <- info.n_hits + 1; info
           | None ->
               let info = { n_hits = 1; examples = 0; kind; first_iter = i;
                            min_repro = "" } in
               Hashtbl.add sigs s info;
               Printf.printf "[iter %d] NEW %s signature: %s\n%!" i
                 (match kind with `Mismatch -> "MISMATCH"
                                | `BothError -> "BOTH-ERROR"
                                | `Crash -> "CRASH") s;
               info
         in
         let dir = Filename.concat !out_dir (sanitize_sig s) in
         mkdir_p dir;
        if info.examples < 3 then begin
          info.examples <- info.examples + 1;
          write_file (Filename.concat dir (Printf.sprintf "%d.ppl" i)) src;
          write_file (Filename.concat dir (Printf.sprintf "%d.tw.out" i))
            (outcome_to_string w);
          if rt.status <> `Exit 0 then
            write_file (Filename.concat dir (Printf.sprintf "%d.rt.out" i))
              (outcome_to_string rt);
          (match !meta_twin_src with
           | Some twin ->
               write_file (Filename.concat dir (Printf.sprintf "%d.twin.ppl" i)) twin
           | None -> ())
        end;
        (* shrink only the first exemplar of a signature; both-error is a
           soft class — shrink mismatches and crashes only *)
        if info.n_hits = 1 && kind <> `BothError then begin
          let small = shrink src s in
          info.min_repro <- small;
          write_file (Filename.concat dir "min.ppl") small;
          if is_meta_signature s then begin
            let h = Hashtbl.hash small in
            Random.full_init [| h |];
            name_counter := 0;
            (match derive_twin small with
             | Some twin ->
                 write_file (Filename.concat dir "min.twin.ppl") twin;
                 let p_out = run_single small in
                 let t_out = run_single twin in
                 write_file (Filename.concat dir "min.tw.out") (outcome_to_string p_out);
                 write_file (Filename.concat dir "min.twin.out") (outcome_to_string t_out)
             | None -> ())
          end else begin
            let w' = run_walker small in
            write_file (Filename.concat dir "min.tw.out") (outcome_to_string w')
          end
        end);
    let done_n = i - !start_iter + 1 in
    if done_n mod 200 = 0 then
      Printf.printf "  ... %d/%d  pass=%d mismatch=%d both-error=%d crash=%d meta-fail=%d distinct-sigs=%d\n%!"
        done_n !count !n_pass !n_mismatch !n_both !n_crash !n_meta_fail (Hashtbl.length sigs)
  done;
  Printf.printf "\n==== pp-fuzz summary (grammar=%s, seed=%d, count=%d) ====\n"
    !grammar !seed !count;
  Printf.printf "PASS       %d (of which %d matched-error)\nMISMATCH   %d\nBOTH-ERROR %d\nCRASH      %d\n"
    !n_pass !n_errpass !n_mismatch !n_both !n_crash;
  Printf.printf "roundtrip  %d checked, %d failed (sexpr->braces->re-read)\n"
    !n_rt_checked !n_rt_fail;
  Printf.printf "metamorphic %d checked, %d failed (single-engine oracle)\n"
    !n_meta_checked !n_meta_fail;
  Printf.printf "distinct signatures: %d\n" (Hashtbl.length sigs);
  let sorted =
    Hashtbl.fold (fun s info acc -> (s, info) :: acc) sigs []
    |> List.sort (fun (_, a) (_, b) -> compare b.n_hits a.n_hits) in
  List.iter (fun (s, info) ->
    Printf.printf "\n[%s] x%d (first at iter %d)\n  %s\n  dir: %s\n"
      (match info.kind with `Mismatch -> "MISMATCH"
                          | `BothError -> "BOTH-ERROR" | `Crash -> "CRASH")
      info.n_hits info.first_iter s
      (Filename.concat !out_dir (sanitize_sig s));
    if info.min_repro <> "" && String.length info.min_repro < 400 then begin
      Printf.printf "  min repro:\n";
      List.iter (fun l -> if l <> "" then Printf.printf "    %s\n" l)
        (String.split_on_char '\n' info.min_repro)
    end
  ) sorted;
  (* CI verdict: BOTH-ERROR is whitelisted (soft class) *)
  if !n_mismatch > 0 || !n_crash > 0 then begin
    Printf.printf "\nRESULT: FAIL (%d mismatches, %d crashes)\n" !n_mismatch !n_crash;
    exit 1
  end else begin
    Printf.printf "\nRESULT: OK (no mismatches or crashes; %d matched-error, %d both-error programs)\n"
      !n_errpass !n_both;
    exit 0
  end
