;;;; M4 thunk adapters and content identities.
(in-package #:pp.runtime)

(defun runtime-thunk-error (message &optional (code "runtime.thunk"))
  (if (fboundp 'language-fail) (language-fail message code) (error "~A" message)))
(defun runtime-thunk-capabilities-hash (caps)
  (hash-concat (cons "caps" (mapcar #'capability-hash caps))))
(defun runtime-thunk-configuration-hash ()
  (runtime-configuration-hash (runtime-configuration-current)))
(defun runtime-thunk-handlers-hash ()
  (hash-concat (cons "handlers" (mapcan (lambda (entry) (list (car entry) (or (cdr entry) "")))
                                   (runtime-dynamic-handler-identities)))))
(defun runtime-thunk-location-hash (location)
  (if location
      (let ((p (source-range-start location)))
        (hash-concat (list "location" (source-range-source location)
                           (canonical-integer-string (position-line p)))))
      nil))
(defun runtime-thunk-content-hash (expression environment type-ann location kind args)
  (let* ((persistent (typep kind 'thunk-kind-persistent))
         (tag (cond (persistent "node-thunk")
                    (type-ann "thunk-typed")
                    (t "thunk")))
         (type-part (and type-ann (hash-expr type-ann)))
         (location-part (and location (runtime-thunk-location-hash location)))
         (arg-parts (if persistent
                        (mapcar (lambda (v) (hash-concat (list "arg" (hash-value v))))
                                (or (thunk-kind-persistent-argument-values kind)
                                    args))
                        nil))
         (capabilities (if persistent
                           (thunk-kind-persistent-captured-caps kind)
                           (runtime-dynamic-capabilities))))
    (hash-concat
     (append (list tag (hash-expr expression))
             (and type-part (list type-part))
             (and location-part (list location-part))
             arg-parts
             (list (env-env-hash environment)
                   (runtime-thunk-capabilities-hash capabilities)
                   (runtime-thunk-configuration-hash)
                   (runtime-thunk-handlers-hash))))))
(defun runtime-thunk-capture-kind (kind arguments)
  (if (typep kind 'thunk-kind-persistent)
      ;; A NIL capability list is an intentional empty capture.
      kind
      (make-persistent-thunk-kind
       (copy-list (runtime-dynamic-capabilities))
       (copy-list arguments))))
(defun runtime-thunk-make-with-hash (expression environment &key name type-ann location (kind :ephemeral) arguments)
  (let* ((persistent (or (eq kind :persistent) (typep kind 'thunk-kind-persistent)))
         (kind (if persistent
                   (runtime-thunk-capture-kind
                    (if (typep kind 'thunk-kind-persistent)
                        kind
                        (make-persistent-thunk-kind
                         (runtime-dynamic-capabilities)
                         (copy-list arguments)))
                    arguments)
                   (make-ephemeral-thunk-kind)))
         (hash (runtime-thunk-content-hash expression environment type-ann location kind arguments))
         (session (runtime-dynamic-session nil))
         (existing (and persistent session (runtime-session-find-thunk session hash))))
    (or existing
        (let ((thunk (make-thunk expression environment :name name :type-ann type-ann
                                 :location location :config-hash (runtime-thunk-configuration-hash)
                                 :hash hash :kind kind)))
          (when (and persistent session) (runtime-session-add-thunk session hash thunk))
          thunk))))
(defun runtime-thunk-make (expression environment &key name type-ann location)
  (runtime-thunk-make-with-hash expression environment :name name :type-ann type-ann :location location))
(defun runtime-thunk-make-node (expression environment &key name arguments)
  (runtime-thunk-make-with-hash expression environment :name name :kind :persistent :arguments arguments))
(defun runtime-thunk-make-typed (expression type-ann location environment)
  (runtime-thunk-make-with-hash expression environment :type-ann type-ann :location location))
(defun runtime-thunk-persistent-p (thunk) (typep (thunk-kind thunk) 'thunk-kind-persistent))
(defun runtime-thunk-captured-capabilities (thunk)
  (if (runtime-thunk-persistent-p thunk) (thunk-kind-persistent-captured-caps (thunk-kind thunk)) nil))
(defun runtime-thunk-arguments (thunk)
  (if (runtime-thunk-persistent-p thunk) (thunk-kind-persistent-argument-values (thunk-kind thunk)) nil))
(defun runtime-thunk-hash (thunk) (thunk-hash thunk))
(defun runtime-thunk-poison (name environment)
  (make-thunk (make-eapply (make-esymbol "error") (list (make-eliteral (make-vstring (format nil "~A: referenced before its definition" name))))) environment))
(defun make-runtime-thunk (&rest args) (apply #'runtime-thunk-make args))
(defun make-runtime-node-thunk (&rest args) (apply #'runtime-thunk-make-node args))
(defun evaluator-thunks-make (&rest args) (apply #'runtime-thunk-make args))
(defun evaluator-thunks-make-node (&rest args) (apply #'runtime-thunk-make-node args))
(defun make-thunk-with-hash (&rest args) (apply #'runtime-thunk-make-with-hash args))
(defun thunk-persistent-p (thunk) (runtime-thunk-persistent-p thunk))
