(executable
 (name main)
 (public_name pp)
 (modules version types hasher blobref codec paths cell surface_tables runtime store journal gcroots desugar
   reader reader_braces printer_braces printer_sexpr comments
   capabilities process scheduler domain_prims fenced island primitives domains evaluator macro
   compiler stabilize vm repl token transport remote store_gc lint main)
 (libraries cryptokit dune-build-info)
 (flags -no-strict-sequence))
