(executable
 (name kernel_unit)
 (libraries pp.kernel))

(executable
 (name repository_unit)
 (libraries pp.kernel pp.runtime unix))

(executable
 (name event_unit)
 (libraries pp.kernel pp.runtime))

(executable
 (name observation_unit)
 (libraries pp.kernel pp.runtime unix))

(executable
 (name lifecycle_unit)
 (libraries pp.kernel pp.runtime unix))

(executable
 (name parser_unit)
 (libraries pp.kernel pp.frontend))
